// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// VirtualizationClusterGroupsPartialUpdateReader is a Reader for the VirtualizationClusterGroupsPartialUpdate structure.
type VirtualizationClusterGroupsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualizationClusterGroupsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVirtualizationClusterGroupsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewVirtualizationClusterGroupsPartialUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewVirtualizationClusterGroupsPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVirtualizationClusterGroupsPartialUpdateOK creates a VirtualizationClusterGroupsPartialUpdateOK with default headers values
func NewVirtualizationClusterGroupsPartialUpdateOK() *VirtualizationClusterGroupsPartialUpdateOK {
	return &VirtualizationClusterGroupsPartialUpdateOK{}
}

/*
VirtualizationClusterGroupsPartialUpdateOK describes a response with status code 200, with default header values.

VirtualizationClusterGroupsPartialUpdateOK virtualization cluster groups partial update o k
*/
type VirtualizationClusterGroupsPartialUpdateOK struct {
	Payload *models.ClusterGroup
}

// IsSuccess returns true when this virtualization cluster groups partial update o k response has a 2xx status code
func (o *VirtualizationClusterGroupsPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this virtualization cluster groups partial update o k response has a 3xx status code
func (o *VirtualizationClusterGroupsPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization cluster groups partial update o k response has a 4xx status code
func (o *VirtualizationClusterGroupsPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this virtualization cluster groups partial update o k response has a 5xx status code
func (o *VirtualizationClusterGroupsPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization cluster groups partial update o k response a status code equal to that given
func (o *VirtualizationClusterGroupsPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *VirtualizationClusterGroupsPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /virtualization/cluster-groups/{id}/][%d] virtualizationClusterGroupsPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *VirtualizationClusterGroupsPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /virtualization/cluster-groups/{id}/][%d] virtualizationClusterGroupsPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *VirtualizationClusterGroupsPartialUpdateOK) GetPayload() *models.ClusterGroup {
	return o.Payload
}

func (o *VirtualizationClusterGroupsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualizationClusterGroupsPartialUpdateBadRequest creates a VirtualizationClusterGroupsPartialUpdateBadRequest with default headers values
func NewVirtualizationClusterGroupsPartialUpdateBadRequest() *VirtualizationClusterGroupsPartialUpdateBadRequest {
	return &VirtualizationClusterGroupsPartialUpdateBadRequest{}
}

/*
VirtualizationClusterGroupsPartialUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type VirtualizationClusterGroupsPartialUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this virtualization cluster groups partial update bad request response has a 2xx status code
func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this virtualization cluster groups partial update bad request response has a 3xx status code
func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization cluster groups partial update bad request response has a 4xx status code
func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this virtualization cluster groups partial update bad request response has a 5xx status code
func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization cluster groups partial update bad request response a status code equal to that given
func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /virtualization/cluster-groups/{id}/][%d] virtualizationClusterGroupsPartialUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) String() string {
	return fmt.Sprintf("[PATCH /virtualization/cluster-groups/{id}/][%d] virtualizationClusterGroupsPartialUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *VirtualizationClusterGroupsPartialUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualizationClusterGroupsPartialUpdateDefault creates a VirtualizationClusterGroupsPartialUpdateDefault with default headers values
func NewVirtualizationClusterGroupsPartialUpdateDefault(code int) *VirtualizationClusterGroupsPartialUpdateDefault {
	return &VirtualizationClusterGroupsPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
VirtualizationClusterGroupsPartialUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type VirtualizationClusterGroupsPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the virtualization cluster groups partial update default response
func (o *VirtualizationClusterGroupsPartialUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this virtualization cluster groups partial update default response has a 2xx status code
func (o *VirtualizationClusterGroupsPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this virtualization cluster groups partial update default response has a 3xx status code
func (o *VirtualizationClusterGroupsPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this virtualization cluster groups partial update default response has a 4xx status code
func (o *VirtualizationClusterGroupsPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this virtualization cluster groups partial update default response has a 5xx status code
func (o *VirtualizationClusterGroupsPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this virtualization cluster groups partial update default response a status code equal to that given
func (o *VirtualizationClusterGroupsPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *VirtualizationClusterGroupsPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /virtualization/cluster-groups/{id}/][%d] virtualization_cluster-groups_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *VirtualizationClusterGroupsPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /virtualization/cluster-groups/{id}/][%d] virtualization_cluster-groups_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *VirtualizationClusterGroupsPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *VirtualizationClusterGroupsPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
