// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// VirtualizationInterfacesCreateReader is a Reader for the VirtualizationInterfacesCreate structure.
type VirtualizationInterfacesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualizationInterfacesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewVirtualizationInterfacesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewVirtualizationInterfacesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewVirtualizationInterfacesCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVirtualizationInterfacesCreateCreated creates a VirtualizationInterfacesCreateCreated with default headers values
func NewVirtualizationInterfacesCreateCreated() *VirtualizationInterfacesCreateCreated {
	return &VirtualizationInterfacesCreateCreated{}
}

/*
VirtualizationInterfacesCreateCreated describes a response with status code 201, with default header values.

VirtualizationInterfacesCreateCreated virtualization interfaces create created
*/
type VirtualizationInterfacesCreateCreated struct {
	Payload *models.VMInterface
}

// IsSuccess returns true when this virtualization interfaces create created response has a 2xx status code
func (o *VirtualizationInterfacesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this virtualization interfaces create created response has a 3xx status code
func (o *VirtualizationInterfacesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization interfaces create created response has a 4xx status code
func (o *VirtualizationInterfacesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this virtualization interfaces create created response has a 5xx status code
func (o *VirtualizationInterfacesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization interfaces create created response a status code equal to that given
func (o *VirtualizationInterfacesCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *VirtualizationInterfacesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /virtualization/interfaces/][%d] virtualizationInterfacesCreateCreated  %+v", 201, o.Payload)
}

func (o *VirtualizationInterfacesCreateCreated) String() string {
	return fmt.Sprintf("[POST /virtualization/interfaces/][%d] virtualizationInterfacesCreateCreated  %+v", 201, o.Payload)
}

func (o *VirtualizationInterfacesCreateCreated) GetPayload() *models.VMInterface {
	return o.Payload
}

func (o *VirtualizationInterfacesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VMInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualizationInterfacesCreateBadRequest creates a VirtualizationInterfacesCreateBadRequest with default headers values
func NewVirtualizationInterfacesCreateBadRequest() *VirtualizationInterfacesCreateBadRequest {
	return &VirtualizationInterfacesCreateBadRequest{}
}

/*
VirtualizationInterfacesCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type VirtualizationInterfacesCreateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this virtualization interfaces create bad request response has a 2xx status code
func (o *VirtualizationInterfacesCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this virtualization interfaces create bad request response has a 3xx status code
func (o *VirtualizationInterfacesCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization interfaces create bad request response has a 4xx status code
func (o *VirtualizationInterfacesCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this virtualization interfaces create bad request response has a 5xx status code
func (o *VirtualizationInterfacesCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization interfaces create bad request response a status code equal to that given
func (o *VirtualizationInterfacesCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *VirtualizationInterfacesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /virtualization/interfaces/][%d] virtualizationInterfacesCreateBadRequest  %+v", 400, o.Payload)
}

func (o *VirtualizationInterfacesCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /virtualization/interfaces/][%d] virtualizationInterfacesCreateBadRequest  %+v", 400, o.Payload)
}

func (o *VirtualizationInterfacesCreateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *VirtualizationInterfacesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualizationInterfacesCreateDefault creates a VirtualizationInterfacesCreateDefault with default headers values
func NewVirtualizationInterfacesCreateDefault(code int) *VirtualizationInterfacesCreateDefault {
	return &VirtualizationInterfacesCreateDefault{
		_statusCode: code,
	}
}

/*
VirtualizationInterfacesCreateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type VirtualizationInterfacesCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the virtualization interfaces create default response
func (o *VirtualizationInterfacesCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this virtualization interfaces create default response has a 2xx status code
func (o *VirtualizationInterfacesCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this virtualization interfaces create default response has a 3xx status code
func (o *VirtualizationInterfacesCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this virtualization interfaces create default response has a 4xx status code
func (o *VirtualizationInterfacesCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this virtualization interfaces create default response has a 5xx status code
func (o *VirtualizationInterfacesCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this virtualization interfaces create default response a status code equal to that given
func (o *VirtualizationInterfacesCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *VirtualizationInterfacesCreateDefault) Error() string {
	return fmt.Sprintf("[POST /virtualization/interfaces/][%d] virtualization_interfaces_create default  %+v", o._statusCode, o.Payload)
}

func (o *VirtualizationInterfacesCreateDefault) String() string {
	return fmt.Sprintf("[POST /virtualization/interfaces/][%d] virtualization_interfaces_create default  %+v", o._statusCode, o.Payload)
}

func (o *VirtualizationInterfacesCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *VirtualizationInterfacesCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
