// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// WirelessWirelessLanGroupsUpdateReader is a Reader for the WirelessWirelessLanGroupsUpdate structure.
type WirelessWirelessLanGroupsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WirelessWirelessLanGroupsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWirelessWirelessLanGroupsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWirelessWirelessLanGroupsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewWirelessWirelessLanGroupsUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewWirelessWirelessLanGroupsUpdateOK creates a WirelessWirelessLanGroupsUpdateOK with default headers values
func NewWirelessWirelessLanGroupsUpdateOK() *WirelessWirelessLanGroupsUpdateOK {
	return &WirelessWirelessLanGroupsUpdateOK{}
}

/*
WirelessWirelessLanGroupsUpdateOK describes a response with status code 200, with default header values.

WirelessWirelessLanGroupsUpdateOK wireless wireless lan groups update o k
*/
type WirelessWirelessLanGroupsUpdateOK struct {
	Payload *models.WirelessLANGroup
}

// IsSuccess returns true when this wireless wireless lan groups update o k response has a 2xx status code
func (o *WirelessWirelessLanGroupsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this wireless wireless lan groups update o k response has a 3xx status code
func (o *WirelessWirelessLanGroupsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this wireless wireless lan groups update o k response has a 4xx status code
func (o *WirelessWirelessLanGroupsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this wireless wireless lan groups update o k response has a 5xx status code
func (o *WirelessWirelessLanGroupsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this wireless wireless lan groups update o k response a status code equal to that given
func (o *WirelessWirelessLanGroupsUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *WirelessWirelessLanGroupsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /wireless/wireless-lan-groups/{id}/][%d] wirelessWirelessLanGroupsUpdateOK  %+v", 200, o.Payload)
}

func (o *WirelessWirelessLanGroupsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /wireless/wireless-lan-groups/{id}/][%d] wirelessWirelessLanGroupsUpdateOK  %+v", 200, o.Payload)
}

func (o *WirelessWirelessLanGroupsUpdateOK) GetPayload() *models.WirelessLANGroup {
	return o.Payload
}

func (o *WirelessWirelessLanGroupsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WirelessLANGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWirelessWirelessLanGroupsUpdateBadRequest creates a WirelessWirelessLanGroupsUpdateBadRequest with default headers values
func NewWirelessWirelessLanGroupsUpdateBadRequest() *WirelessWirelessLanGroupsUpdateBadRequest {
	return &WirelessWirelessLanGroupsUpdateBadRequest{}
}

/*
WirelessWirelessLanGroupsUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type WirelessWirelessLanGroupsUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this wireless wireless lan groups update bad request response has a 2xx status code
func (o *WirelessWirelessLanGroupsUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this wireless wireless lan groups update bad request response has a 3xx status code
func (o *WirelessWirelessLanGroupsUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this wireless wireless lan groups update bad request response has a 4xx status code
func (o *WirelessWirelessLanGroupsUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this wireless wireless lan groups update bad request response has a 5xx status code
func (o *WirelessWirelessLanGroupsUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this wireless wireless lan groups update bad request response a status code equal to that given
func (o *WirelessWirelessLanGroupsUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *WirelessWirelessLanGroupsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /wireless/wireless-lan-groups/{id}/][%d] wirelessWirelessLanGroupsUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *WirelessWirelessLanGroupsUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /wireless/wireless-lan-groups/{id}/][%d] wirelessWirelessLanGroupsUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *WirelessWirelessLanGroupsUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *WirelessWirelessLanGroupsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWirelessWirelessLanGroupsUpdateDefault creates a WirelessWirelessLanGroupsUpdateDefault with default headers values
func NewWirelessWirelessLanGroupsUpdateDefault(code int) *WirelessWirelessLanGroupsUpdateDefault {
	return &WirelessWirelessLanGroupsUpdateDefault{
		_statusCode: code,
	}
}

/*
WirelessWirelessLanGroupsUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type WirelessWirelessLanGroupsUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the wireless wireless lan groups update default response
func (o *WirelessWirelessLanGroupsUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this wireless wireless lan groups update default response has a 2xx status code
func (o *WirelessWirelessLanGroupsUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this wireless wireless lan groups update default response has a 3xx status code
func (o *WirelessWirelessLanGroupsUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this wireless wireless lan groups update default response has a 4xx status code
func (o *WirelessWirelessLanGroupsUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this wireless wireless lan groups update default response has a 5xx status code
func (o *WirelessWirelessLanGroupsUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this wireless wireless lan groups update default response a status code equal to that given
func (o *WirelessWirelessLanGroupsUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *WirelessWirelessLanGroupsUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /wireless/wireless-lan-groups/{id}/][%d] wireless_wireless-lan-groups_update default  %+v", o._statusCode, o.Payload)
}

func (o *WirelessWirelessLanGroupsUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /wireless/wireless-lan-groups/{id}/][%d] wireless_wireless-lan-groups_update default  %+v", o._statusCode, o.Payload)
}

func (o *WirelessWirelessLanGroupsUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *WirelessWirelessLanGroupsUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
