// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// ExtrasCustomLinksUpdateReader is a Reader for the ExtrasCustomLinksUpdate structure.
type ExtrasCustomLinksUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasCustomLinksUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtrasCustomLinksUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtrasCustomLinksUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewExtrasCustomLinksUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExtrasCustomLinksUpdateOK creates a ExtrasCustomLinksUpdateOK with default headers values
func NewExtrasCustomLinksUpdateOK() *ExtrasCustomLinksUpdateOK {
	return &ExtrasCustomLinksUpdateOK{}
}

/*
ExtrasCustomLinksUpdateOK describes a response with status code 200, with default header values.

ExtrasCustomLinksUpdateOK extras custom links update o k
*/
type ExtrasCustomLinksUpdateOK struct {
	Payload *models.CustomLink
}

// IsSuccess returns true when this extras custom links update o k response has a 2xx status code
func (o *ExtrasCustomLinksUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras custom links update o k response has a 3xx status code
func (o *ExtrasCustomLinksUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras custom links update o k response has a 4xx status code
func (o *ExtrasCustomLinksUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras custom links update o k response has a 5xx status code
func (o *ExtrasCustomLinksUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this extras custom links update o k response a status code equal to that given
func (o *ExtrasCustomLinksUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *ExtrasCustomLinksUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /extras/custom-links/{id}/][%d] extrasCustomLinksUpdateOK  %+v", 200, o.Payload)
}

func (o *ExtrasCustomLinksUpdateOK) String() string {
	return fmt.Sprintf("[PUT /extras/custom-links/{id}/][%d] extrasCustomLinksUpdateOK  %+v", 200, o.Payload)
}

func (o *ExtrasCustomLinksUpdateOK) GetPayload() *models.CustomLink {
	return o.Payload
}

func (o *ExtrasCustomLinksUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomLink)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtrasCustomLinksUpdateBadRequest creates a ExtrasCustomLinksUpdateBadRequest with default headers values
func NewExtrasCustomLinksUpdateBadRequest() *ExtrasCustomLinksUpdateBadRequest {
	return &ExtrasCustomLinksUpdateBadRequest{}
}

/*
ExtrasCustomLinksUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ExtrasCustomLinksUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this extras custom links update bad request response has a 2xx status code
func (o *ExtrasCustomLinksUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this extras custom links update bad request response has a 3xx status code
func (o *ExtrasCustomLinksUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras custom links update bad request response has a 4xx status code
func (o *ExtrasCustomLinksUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this extras custom links update bad request response has a 5xx status code
func (o *ExtrasCustomLinksUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this extras custom links update bad request response a status code equal to that given
func (o *ExtrasCustomLinksUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ExtrasCustomLinksUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /extras/custom-links/{id}/][%d] extrasCustomLinksUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasCustomLinksUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /extras/custom-links/{id}/][%d] extrasCustomLinksUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasCustomLinksUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasCustomLinksUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtrasCustomLinksUpdateDefault creates a ExtrasCustomLinksUpdateDefault with default headers values
func NewExtrasCustomLinksUpdateDefault(code int) *ExtrasCustomLinksUpdateDefault {
	return &ExtrasCustomLinksUpdateDefault{
		_statusCode: code,
	}
}

/*
ExtrasCustomLinksUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type ExtrasCustomLinksUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the extras custom links update default response
func (o *ExtrasCustomLinksUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this extras custom links update default response has a 2xx status code
func (o *ExtrasCustomLinksUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this extras custom links update default response has a 3xx status code
func (o *ExtrasCustomLinksUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this extras custom links update default response has a 4xx status code
func (o *ExtrasCustomLinksUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this extras custom links update default response has a 5xx status code
func (o *ExtrasCustomLinksUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this extras custom links update default response a status code equal to that given
func (o *ExtrasCustomLinksUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ExtrasCustomLinksUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /extras/custom-links/{id}/][%d] extras_custom-links_update default  %+v", o._statusCode, o.Payload)
}

func (o *ExtrasCustomLinksUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /extras/custom-links/{id}/][%d] extras_custom-links_update default  %+v", o._statusCode, o.Payload)
}

func (o *ExtrasCustomLinksUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasCustomLinksUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
