// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// ExtrasImageAttachmentsCreateReader is a Reader for the ExtrasImageAttachmentsCreate structure.
type ExtrasImageAttachmentsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasImageAttachmentsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewExtrasImageAttachmentsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtrasImageAttachmentsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExtrasImageAttachmentsCreateCreated creates a ExtrasImageAttachmentsCreateCreated with default headers values
func NewExtrasImageAttachmentsCreateCreated() *ExtrasImageAttachmentsCreateCreated {
	return &ExtrasImageAttachmentsCreateCreated{}
}

/*
ExtrasImageAttachmentsCreateCreated describes a response with status code 201, with default header values.

ExtrasImageAttachmentsCreateCreated extras image attachments create created
*/
type ExtrasImageAttachmentsCreateCreated struct {
	Payload *models.ImageAttachment
}

// IsSuccess returns true when this extras image attachments create created response has a 2xx status code
func (o *ExtrasImageAttachmentsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras image attachments create created response has a 3xx status code
func (o *ExtrasImageAttachmentsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras image attachments create created response has a 4xx status code
func (o *ExtrasImageAttachmentsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras image attachments create created response has a 5xx status code
func (o *ExtrasImageAttachmentsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this extras image attachments create created response a status code equal to that given
func (o *ExtrasImageAttachmentsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *ExtrasImageAttachmentsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /extras/image-attachments/][%d] extrasImageAttachmentsCreateCreated  %+v", 201, o.Payload)
}

func (o *ExtrasImageAttachmentsCreateCreated) String() string {
	return fmt.Sprintf("[POST /extras/image-attachments/][%d] extrasImageAttachmentsCreateCreated  %+v", 201, o.Payload)
}

func (o *ExtrasImageAttachmentsCreateCreated) GetPayload() *models.ImageAttachment {
	return o.Payload
}

func (o *ExtrasImageAttachmentsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageAttachment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtrasImageAttachmentsCreateBadRequest creates a ExtrasImageAttachmentsCreateBadRequest with default headers values
func NewExtrasImageAttachmentsCreateBadRequest() *ExtrasImageAttachmentsCreateBadRequest {
	return &ExtrasImageAttachmentsCreateBadRequest{}
}

/*
ExtrasImageAttachmentsCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ExtrasImageAttachmentsCreateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this extras image attachments create bad request response has a 2xx status code
func (o *ExtrasImageAttachmentsCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this extras image attachments create bad request response has a 3xx status code
func (o *ExtrasImageAttachmentsCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras image attachments create bad request response has a 4xx status code
func (o *ExtrasImageAttachmentsCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this extras image attachments create bad request response has a 5xx status code
func (o *ExtrasImageAttachmentsCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this extras image attachments create bad request response a status code equal to that given
func (o *ExtrasImageAttachmentsCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ExtrasImageAttachmentsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /extras/image-attachments/][%d] extrasImageAttachmentsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasImageAttachmentsCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /extras/image-attachments/][%d] extrasImageAttachmentsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasImageAttachmentsCreateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasImageAttachmentsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
