// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// ExtrasConfigContextsBulkUpdateReader is a Reader for the ExtrasConfigContextsBulkUpdate structure.
type ExtrasConfigContextsBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasConfigContextsBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtrasConfigContextsBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtrasConfigContextsBulkUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewExtrasConfigContextsBulkUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExtrasConfigContextsBulkUpdateOK creates a ExtrasConfigContextsBulkUpdateOK with default headers values
func NewExtrasConfigContextsBulkUpdateOK() *ExtrasConfigContextsBulkUpdateOK {
	return &ExtrasConfigContextsBulkUpdateOK{}
}

/*
ExtrasConfigContextsBulkUpdateOK describes a response with status code 200, with default header values.

ExtrasConfigContextsBulkUpdateOK extras config contexts bulk update o k
*/
type ExtrasConfigContextsBulkUpdateOK struct {
	Payload *models.ConfigContext
}

// IsSuccess returns true when this extras config contexts bulk update o k response has a 2xx status code
func (o *ExtrasConfigContextsBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras config contexts bulk update o k response has a 3xx status code
func (o *ExtrasConfigContextsBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras config contexts bulk update o k response has a 4xx status code
func (o *ExtrasConfigContextsBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras config contexts bulk update o k response has a 5xx status code
func (o *ExtrasConfigContextsBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this extras config contexts bulk update o k response a status code equal to that given
func (o *ExtrasConfigContextsBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *ExtrasConfigContextsBulkUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /extras/config-contexts/][%d] extrasConfigContextsBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *ExtrasConfigContextsBulkUpdateOK) String() string {
	return fmt.Sprintf("[PUT /extras/config-contexts/][%d] extrasConfigContextsBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *ExtrasConfigContextsBulkUpdateOK) GetPayload() *models.ConfigContext {
	return o.Payload
}

func (o *ExtrasConfigContextsBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtrasConfigContextsBulkUpdateBadRequest creates a ExtrasConfigContextsBulkUpdateBadRequest with default headers values
func NewExtrasConfigContextsBulkUpdateBadRequest() *ExtrasConfigContextsBulkUpdateBadRequest {
	return &ExtrasConfigContextsBulkUpdateBadRequest{}
}

/*
ExtrasConfigContextsBulkUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ExtrasConfigContextsBulkUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this extras config contexts bulk update bad request response has a 2xx status code
func (o *ExtrasConfigContextsBulkUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this extras config contexts bulk update bad request response has a 3xx status code
func (o *ExtrasConfigContextsBulkUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras config contexts bulk update bad request response has a 4xx status code
func (o *ExtrasConfigContextsBulkUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this extras config contexts bulk update bad request response has a 5xx status code
func (o *ExtrasConfigContextsBulkUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this extras config contexts bulk update bad request response a status code equal to that given
func (o *ExtrasConfigContextsBulkUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ExtrasConfigContextsBulkUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /extras/config-contexts/][%d] extrasConfigContextsBulkUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasConfigContextsBulkUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /extras/config-contexts/][%d] extrasConfigContextsBulkUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasConfigContextsBulkUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasConfigContextsBulkUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtrasConfigContextsBulkUpdateDefault creates a ExtrasConfigContextsBulkUpdateDefault with default headers values
func NewExtrasConfigContextsBulkUpdateDefault(code int) *ExtrasConfigContextsBulkUpdateDefault {
	return &ExtrasConfigContextsBulkUpdateDefault{
		_statusCode: code,
	}
}

/*
ExtrasConfigContextsBulkUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type ExtrasConfigContextsBulkUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the extras config contexts bulk update default response
func (o *ExtrasConfigContextsBulkUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this extras config contexts bulk update default response has a 2xx status code
func (o *ExtrasConfigContextsBulkUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this extras config contexts bulk update default response has a 3xx status code
func (o *ExtrasConfigContextsBulkUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this extras config contexts bulk update default response has a 4xx status code
func (o *ExtrasConfigContextsBulkUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this extras config contexts bulk update default response has a 5xx status code
func (o *ExtrasConfigContextsBulkUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this extras config contexts bulk update default response a status code equal to that given
func (o *ExtrasConfigContextsBulkUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ExtrasConfigContextsBulkUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /extras/config-contexts/][%d] extras_config-contexts_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *ExtrasConfigContextsBulkUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /extras/config-contexts/][%d] extras_config-contexts_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *ExtrasConfigContextsBulkUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasConfigContextsBulkUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
