// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// ExtrasCustomFieldsReadReader is a Reader for the ExtrasCustomFieldsRead structure.
type ExtrasCustomFieldsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasCustomFieldsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtrasCustomFieldsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtrasCustomFieldsReadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewExtrasCustomFieldsReadDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExtrasCustomFieldsReadOK creates a ExtrasCustomFieldsReadOK with default headers values
func NewExtrasCustomFieldsReadOK() *ExtrasCustomFieldsReadOK {
	return &ExtrasCustomFieldsReadOK{}
}

/*
ExtrasCustomFieldsReadOK describes a response with status code 200, with default header values.

ExtrasCustomFieldsReadOK extras custom fields read o k
*/
type ExtrasCustomFieldsReadOK struct {
	Payload *models.CustomField
}

// IsSuccess returns true when this extras custom fields read o k response has a 2xx status code
func (o *ExtrasCustomFieldsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras custom fields read o k response has a 3xx status code
func (o *ExtrasCustomFieldsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras custom fields read o k response has a 4xx status code
func (o *ExtrasCustomFieldsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras custom fields read o k response has a 5xx status code
func (o *ExtrasCustomFieldsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this extras custom fields read o k response a status code equal to that given
func (o *ExtrasCustomFieldsReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *ExtrasCustomFieldsReadOK) Error() string {
	return fmt.Sprintf("[GET /extras/custom-fields/{id}/][%d] extrasCustomFieldsReadOK  %+v", 200, o.Payload)
}

func (o *ExtrasCustomFieldsReadOK) String() string {
	return fmt.Sprintf("[GET /extras/custom-fields/{id}/][%d] extrasCustomFieldsReadOK  %+v", 200, o.Payload)
}

func (o *ExtrasCustomFieldsReadOK) GetPayload() *models.CustomField {
	return o.Payload
}

func (o *ExtrasCustomFieldsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomField)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtrasCustomFieldsReadBadRequest creates a ExtrasCustomFieldsReadBadRequest with default headers values
func NewExtrasCustomFieldsReadBadRequest() *ExtrasCustomFieldsReadBadRequest {
	return &ExtrasCustomFieldsReadBadRequest{}
}

/*
ExtrasCustomFieldsReadBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ExtrasCustomFieldsReadBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this extras custom fields read bad request response has a 2xx status code
func (o *ExtrasCustomFieldsReadBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this extras custom fields read bad request response has a 3xx status code
func (o *ExtrasCustomFieldsReadBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras custom fields read bad request response has a 4xx status code
func (o *ExtrasCustomFieldsReadBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this extras custom fields read bad request response has a 5xx status code
func (o *ExtrasCustomFieldsReadBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this extras custom fields read bad request response a status code equal to that given
func (o *ExtrasCustomFieldsReadBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ExtrasCustomFieldsReadBadRequest) Error() string {
	return fmt.Sprintf("[GET /extras/custom-fields/{id}/][%d] extrasCustomFieldsReadBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasCustomFieldsReadBadRequest) String() string {
	return fmt.Sprintf("[GET /extras/custom-fields/{id}/][%d] extrasCustomFieldsReadBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasCustomFieldsReadBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasCustomFieldsReadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtrasCustomFieldsReadDefault creates a ExtrasCustomFieldsReadDefault with default headers values
func NewExtrasCustomFieldsReadDefault(code int) *ExtrasCustomFieldsReadDefault {
	return &ExtrasCustomFieldsReadDefault{
		_statusCode: code,
	}
}

/*
ExtrasCustomFieldsReadDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type ExtrasCustomFieldsReadDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the extras custom fields read default response
func (o *ExtrasCustomFieldsReadDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this extras custom fields read default response has a 2xx status code
func (o *ExtrasCustomFieldsReadDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this extras custom fields read default response has a 3xx status code
func (o *ExtrasCustomFieldsReadDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this extras custom fields read default response has a 4xx status code
func (o *ExtrasCustomFieldsReadDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this extras custom fields read default response has a 5xx status code
func (o *ExtrasCustomFieldsReadDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this extras custom fields read default response a status code equal to that given
func (o *ExtrasCustomFieldsReadDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ExtrasCustomFieldsReadDefault) Error() string {
	return fmt.Sprintf("[GET /extras/custom-fields/{id}/][%d] extras_custom-fields_read default  %+v", o._statusCode, o.Payload)
}

func (o *ExtrasCustomFieldsReadDefault) String() string {
	return fmt.Sprintf("[GET /extras/custom-fields/{id}/][%d] extras_custom-fields_read default  %+v", o._statusCode, o.Payload)
}

func (o *ExtrasCustomFieldsReadDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasCustomFieldsReadDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
