// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExtrasTagsDeleteReader is a Reader for the ExtrasTagsDelete structure.
type ExtrasTagsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasTagsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewExtrasTagsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtrasTagsDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewExtrasTagsDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExtrasTagsDeleteNoContent creates a ExtrasTagsDeleteNoContent with default headers values
func NewExtrasTagsDeleteNoContent() *ExtrasTagsDeleteNoContent {
	return &ExtrasTagsDeleteNoContent{}
}

/*
ExtrasTagsDeleteNoContent describes a response with status code 204, with default header values.

ExtrasTagsDeleteNoContent extras tags delete no content
*/
type ExtrasTagsDeleteNoContent struct {
}

// IsSuccess returns true when this extras tags delete no content response has a 2xx status code
func (o *ExtrasTagsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras tags delete no content response has a 3xx status code
func (o *ExtrasTagsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras tags delete no content response has a 4xx status code
func (o *ExtrasTagsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras tags delete no content response has a 5xx status code
func (o *ExtrasTagsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this extras tags delete no content response a status code equal to that given
func (o *ExtrasTagsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *ExtrasTagsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /extras/tags/{id}/][%d] extrasTagsDeleteNoContent ", 204)
}

func (o *ExtrasTagsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /extras/tags/{id}/][%d] extrasTagsDeleteNoContent ", 204)
}

func (o *ExtrasTagsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtrasTagsDeleteBadRequest creates a ExtrasTagsDeleteBadRequest with default headers values
func NewExtrasTagsDeleteBadRequest() *ExtrasTagsDeleteBadRequest {
	return &ExtrasTagsDeleteBadRequest{}
}

/*
ExtrasTagsDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ExtrasTagsDeleteBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this extras tags delete bad request response has a 2xx status code
func (o *ExtrasTagsDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this extras tags delete bad request response has a 3xx status code
func (o *ExtrasTagsDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras tags delete bad request response has a 4xx status code
func (o *ExtrasTagsDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this extras tags delete bad request response has a 5xx status code
func (o *ExtrasTagsDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this extras tags delete bad request response a status code equal to that given
func (o *ExtrasTagsDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ExtrasTagsDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /extras/tags/{id}/][%d] extrasTagsDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasTagsDeleteBadRequest) String() string {
	return fmt.Sprintf("[DELETE /extras/tags/{id}/][%d] extrasTagsDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *ExtrasTagsDeleteBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasTagsDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtrasTagsDeleteDefault creates a ExtrasTagsDeleteDefault with default headers values
func NewExtrasTagsDeleteDefault(code int) *ExtrasTagsDeleteDefault {
	return &ExtrasTagsDeleteDefault{
		_statusCode: code,
	}
}

/*
ExtrasTagsDeleteDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type ExtrasTagsDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the extras tags delete default response
func (o *ExtrasTagsDeleteDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this extras tags delete default response has a 2xx status code
func (o *ExtrasTagsDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this extras tags delete default response has a 3xx status code
func (o *ExtrasTagsDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this extras tags delete default response has a 4xx status code
func (o *ExtrasTagsDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this extras tags delete default response has a 5xx status code
func (o *ExtrasTagsDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this extras tags delete default response a status code equal to that given
func (o *ExtrasTagsDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ExtrasTagsDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /extras/tags/{id}/][%d] extras_tags_delete default  %+v", o._statusCode, o.Payload)
}

func (o *ExtrasTagsDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /extras/tags/{id}/][%d] extras_tags_delete default  %+v", o._statusCode, o.Payload)
}

func (o *ExtrasTagsDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *ExtrasTagsDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
