// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCircuitsProviderAccountsListParams creates a new CircuitsProviderAccountsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCircuitsProviderAccountsListParams() *CircuitsProviderAccountsListParams {
	return &CircuitsProviderAccountsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCircuitsProviderAccountsListParamsWithTimeout creates a new CircuitsProviderAccountsListParams object
// with the ability to set a timeout on a request.
func NewCircuitsProviderAccountsListParamsWithTimeout(timeout time.Duration) *CircuitsProviderAccountsListParams {
	return &CircuitsProviderAccountsListParams{
		timeout: timeout,
	}
}

// NewCircuitsProviderAccountsListParamsWithContext creates a new CircuitsProviderAccountsListParams object
// with the ability to set a context for a request.
func NewCircuitsProviderAccountsListParamsWithContext(ctx context.Context) *CircuitsProviderAccountsListParams {
	return &CircuitsProviderAccountsListParams{
		Context: ctx,
	}
}

// NewCircuitsProviderAccountsListParamsWithHTTPClient creates a new CircuitsProviderAccountsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewCircuitsProviderAccountsListParamsWithHTTPClient(client *http.Client) *CircuitsProviderAccountsListParams {
	return &CircuitsProviderAccountsListParams{
		HTTPClient: client,
	}
}

/*
CircuitsProviderAccountsListParams contains all the parameters to send to the API endpoint

	for the circuits provider accounts list operation.

	Typically these are written to a http.Request.
*/
type CircuitsProviderAccountsListParams struct {

	// Account.
	Account *string

	// AccountEmpty.
	AccountEmpty *string

	// AccountIc.
	AccountIc *string

	// AccountIe.
	AccountIe *string

	// AccountIew.
	AccountIew *string

	// AccountIsw.
	AccountIsw *string

	// Accountn.
	Accountn *string

	// AccountNic.
	AccountNic *string

	// AccountNie.
	AccountNie *string

	// AccountNiew.
	AccountNiew *string

	// AccountNisw.
	AccountNisw *string

	// Created.
	Created *string

	// CreatedGt.
	CreatedGt *string

	// CreatedGte.
	CreatedGte *string

	// CreatedLt.
	CreatedLt *string

	// CreatedLte.
	CreatedLte *string

	// Createdn.
	Createdn *string

	// CreatedByRequest.
	CreatedByRequest *string

	// Description.
	Description *string

	// DescriptionEmpty.
	DescriptionEmpty *string

	// DescriptionIc.
	DescriptionIc *string

	// DescriptionIe.
	DescriptionIe *string

	// DescriptionIew.
	DescriptionIew *string

	// DescriptionIsw.
	DescriptionIsw *string

	// Descriptionn.
	Descriptionn *string

	// DescriptionNic.
	DescriptionNic *string

	// DescriptionNie.
	DescriptionNie *string

	// DescriptionNiew.
	DescriptionNiew *string

	// DescriptionNisw.
	DescriptionNisw *string

	// ID.
	ID *string

	// IDGt.
	IDGt *string

	// IDGte.
	IDGte *string

	// IDLt.
	IDLt *string

	// IDLte.
	IDLte *string

	// IDn.
	IDn *string

	// LastUpdated.
	LastUpdated *string

	// LastUpdatedGt.
	LastUpdatedGt *string

	// LastUpdatedGte.
	LastUpdatedGte *string

	// LastUpdatedLt.
	LastUpdatedLt *string

	// LastUpdatedLte.
	LastUpdatedLte *string

	// LastUpdatedn.
	LastUpdatedn *string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	// Name.
	Name *string

	// NameEmpty.
	NameEmpty *string

	// NameIc.
	NameIc *string

	// NameIe.
	NameIe *string

	// NameIew.
	NameIew *string

	// NameIsw.
	NameIsw *string

	// Namen.
	Namen *string

	// NameNic.
	NameNic *string

	// NameNie.
	NameNie *string

	// NameNiew.
	NameNiew *string

	// NameNisw.
	NameNisw *string

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	/* Ordering.

	   Which field to use when ordering the results.
	*/
	Ordering *string

	// Provider.
	Provider *string

	// Providern.
	Providern *string

	// ProviderID.
	ProviderID *string

	// ProviderIDn.
	ProviderIDn *string

	// Q.
	Q *string

	// Tag.
	Tag *string

	// Tagn.
	Tagn *string

	// UpdatedByRequest.
	UpdatedByRequest *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the circuits provider accounts list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CircuitsProviderAccountsListParams) WithDefaults() *CircuitsProviderAccountsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the circuits provider accounts list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CircuitsProviderAccountsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithTimeout(timeout time.Duration) *CircuitsProviderAccountsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithContext(ctx context.Context) *CircuitsProviderAccountsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithHTTPClient(client *http.Client) *CircuitsProviderAccountsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccount adds the account to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccount(account *string) *CircuitsProviderAccountsListParams {
	o.SetAccount(account)
	return o
}

// SetAccount adds the account to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccount(account *string) {
	o.Account = account
}

// WithAccountEmpty adds the accountEmpty to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountEmpty(accountEmpty *string) *CircuitsProviderAccountsListParams {
	o.SetAccountEmpty(accountEmpty)
	return o
}

// SetAccountEmpty adds the accountEmpty to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountEmpty(accountEmpty *string) {
	o.AccountEmpty = accountEmpty
}

// WithAccountIc adds the accountIc to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountIc(accountIc *string) *CircuitsProviderAccountsListParams {
	o.SetAccountIc(accountIc)
	return o
}

// SetAccountIc adds the accountIc to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountIc(accountIc *string) {
	o.AccountIc = accountIc
}

// WithAccountIe adds the accountIe to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountIe(accountIe *string) *CircuitsProviderAccountsListParams {
	o.SetAccountIe(accountIe)
	return o
}

// SetAccountIe adds the accountIe to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountIe(accountIe *string) {
	o.AccountIe = accountIe
}

// WithAccountIew adds the accountIew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountIew(accountIew *string) *CircuitsProviderAccountsListParams {
	o.SetAccountIew(accountIew)
	return o
}

// SetAccountIew adds the accountIew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountIew(accountIew *string) {
	o.AccountIew = accountIew
}

// WithAccountIsw adds the accountIsw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountIsw(accountIsw *string) *CircuitsProviderAccountsListParams {
	o.SetAccountIsw(accountIsw)
	return o
}

// SetAccountIsw adds the accountIsw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountIsw(accountIsw *string) {
	o.AccountIsw = accountIsw
}

// WithAccountn adds the accountn to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountn(accountn *string) *CircuitsProviderAccountsListParams {
	o.SetAccountn(accountn)
	return o
}

// SetAccountn adds the accountN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountn(accountn *string) {
	o.Accountn = accountn
}

// WithAccountNic adds the accountNic to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountNic(accountNic *string) *CircuitsProviderAccountsListParams {
	o.SetAccountNic(accountNic)
	return o
}

// SetAccountNic adds the accountNic to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountNic(accountNic *string) {
	o.AccountNic = accountNic
}

// WithAccountNie adds the accountNie to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountNie(accountNie *string) *CircuitsProviderAccountsListParams {
	o.SetAccountNie(accountNie)
	return o
}

// SetAccountNie adds the accountNie to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountNie(accountNie *string) {
	o.AccountNie = accountNie
}

// WithAccountNiew adds the accountNiew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountNiew(accountNiew *string) *CircuitsProviderAccountsListParams {
	o.SetAccountNiew(accountNiew)
	return o
}

// SetAccountNiew adds the accountNiew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountNiew(accountNiew *string) {
	o.AccountNiew = accountNiew
}

// WithAccountNisw adds the accountNisw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithAccountNisw(accountNisw *string) *CircuitsProviderAccountsListParams {
	o.SetAccountNisw(accountNisw)
	return o
}

// SetAccountNisw adds the accountNisw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetAccountNisw(accountNisw *string) {
	o.AccountNisw = accountNisw
}

// WithCreated adds the created to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithCreated(created *string) *CircuitsProviderAccountsListParams {
	o.SetCreated(created)
	return o
}

// SetCreated adds the created to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetCreated(created *string) {
	o.Created = created
}

// WithCreatedGt adds the createdGt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithCreatedGt(createdGt *string) *CircuitsProviderAccountsListParams {
	o.SetCreatedGt(createdGt)
	return o
}

// SetCreatedGt adds the createdGt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetCreatedGt(createdGt *string) {
	o.CreatedGt = createdGt
}

// WithCreatedGte adds the createdGte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithCreatedGte(createdGte *string) *CircuitsProviderAccountsListParams {
	o.SetCreatedGte(createdGte)
	return o
}

// SetCreatedGte adds the createdGte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetCreatedGte(createdGte *string) {
	o.CreatedGte = createdGte
}

// WithCreatedLt adds the createdLt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithCreatedLt(createdLt *string) *CircuitsProviderAccountsListParams {
	o.SetCreatedLt(createdLt)
	return o
}

// SetCreatedLt adds the createdLt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetCreatedLt(createdLt *string) {
	o.CreatedLt = createdLt
}

// WithCreatedLte adds the createdLte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithCreatedLte(createdLte *string) *CircuitsProviderAccountsListParams {
	o.SetCreatedLte(createdLte)
	return o
}

// SetCreatedLte adds the createdLte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetCreatedLte(createdLte *string) {
	o.CreatedLte = createdLte
}

// WithCreatedn adds the createdn to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithCreatedn(createdn *string) *CircuitsProviderAccountsListParams {
	o.SetCreatedn(createdn)
	return o
}

// SetCreatedn adds the createdN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetCreatedn(createdn *string) {
	o.Createdn = createdn
}

// WithCreatedByRequest adds the createdByRequest to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithCreatedByRequest(createdByRequest *string) *CircuitsProviderAccountsListParams {
	o.SetCreatedByRequest(createdByRequest)
	return o
}

// SetCreatedByRequest adds the createdByRequest to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetCreatedByRequest(createdByRequest *string) {
	o.CreatedByRequest = createdByRequest
}

// WithDescription adds the description to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescription(description *string) *CircuitsProviderAccountsListParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescription(description *string) {
	o.Description = description
}

// WithDescriptionEmpty adds the descriptionEmpty to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionEmpty(descriptionEmpty *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionEmpty(descriptionEmpty)
	return o
}

// SetDescriptionEmpty adds the descriptionEmpty to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionEmpty(descriptionEmpty *string) {
	o.DescriptionEmpty = descriptionEmpty
}

// WithDescriptionIc adds the descriptionIc to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionIc(descriptionIc *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionIc(descriptionIc)
	return o
}

// SetDescriptionIc adds the descriptionIc to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionIc(descriptionIc *string) {
	o.DescriptionIc = descriptionIc
}

// WithDescriptionIe adds the descriptionIe to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionIe(descriptionIe *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionIe(descriptionIe)
	return o
}

// SetDescriptionIe adds the descriptionIe to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionIe(descriptionIe *string) {
	o.DescriptionIe = descriptionIe
}

// WithDescriptionIew adds the descriptionIew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionIew(descriptionIew *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionIew(descriptionIew)
	return o
}

// SetDescriptionIew adds the descriptionIew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionIew(descriptionIew *string) {
	o.DescriptionIew = descriptionIew
}

// WithDescriptionIsw adds the descriptionIsw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionIsw(descriptionIsw *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionIsw(descriptionIsw)
	return o
}

// SetDescriptionIsw adds the descriptionIsw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionIsw(descriptionIsw *string) {
	o.DescriptionIsw = descriptionIsw
}

// WithDescriptionn adds the descriptionn to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionn(descriptionn *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionn(descriptionn)
	return o
}

// SetDescriptionn adds the descriptionN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionn(descriptionn *string) {
	o.Descriptionn = descriptionn
}

// WithDescriptionNic adds the descriptionNic to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionNic(descriptionNic *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionNic(descriptionNic)
	return o
}

// SetDescriptionNic adds the descriptionNic to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionNic(descriptionNic *string) {
	o.DescriptionNic = descriptionNic
}

// WithDescriptionNie adds the descriptionNie to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionNie(descriptionNie *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionNie(descriptionNie)
	return o
}

// SetDescriptionNie adds the descriptionNie to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionNie(descriptionNie *string) {
	o.DescriptionNie = descriptionNie
}

// WithDescriptionNiew adds the descriptionNiew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionNiew(descriptionNiew *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionNiew(descriptionNiew)
	return o
}

// SetDescriptionNiew adds the descriptionNiew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionNiew(descriptionNiew *string) {
	o.DescriptionNiew = descriptionNiew
}

// WithDescriptionNisw adds the descriptionNisw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithDescriptionNisw(descriptionNisw *string) *CircuitsProviderAccountsListParams {
	o.SetDescriptionNisw(descriptionNisw)
	return o
}

// SetDescriptionNisw adds the descriptionNisw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetDescriptionNisw(descriptionNisw *string) {
	o.DescriptionNisw = descriptionNisw
}

// WithID adds the id to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithID(id *string) *CircuitsProviderAccountsListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetID(id *string) {
	o.ID = id
}

// WithIDGt adds the iDGt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithIDGt(iDGt *string) *CircuitsProviderAccountsListParams {
	o.SetIDGt(iDGt)
	return o
}

// SetIDGt adds the idGt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetIDGt(iDGt *string) {
	o.IDGt = iDGt
}

// WithIDGte adds the iDGte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithIDGte(iDGte *string) *CircuitsProviderAccountsListParams {
	o.SetIDGte(iDGte)
	return o
}

// SetIDGte adds the idGte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetIDGte(iDGte *string) {
	o.IDGte = iDGte
}

// WithIDLt adds the iDLt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithIDLt(iDLt *string) *CircuitsProviderAccountsListParams {
	o.SetIDLt(iDLt)
	return o
}

// SetIDLt adds the idLt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetIDLt(iDLt *string) {
	o.IDLt = iDLt
}

// WithIDLte adds the iDLte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithIDLte(iDLte *string) *CircuitsProviderAccountsListParams {
	o.SetIDLte(iDLte)
	return o
}

// SetIDLte adds the idLte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetIDLte(iDLte *string) {
	o.IDLte = iDLte
}

// WithIDn adds the iDn to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithIDn(iDn *string) *CircuitsProviderAccountsListParams {
	o.SetIDn(iDn)
	return o
}

// SetIDn adds the idN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetIDn(iDn *string) {
	o.IDn = iDn
}

// WithLastUpdated adds the lastUpdated to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithLastUpdated(lastUpdated *string) *CircuitsProviderAccountsListParams {
	o.SetLastUpdated(lastUpdated)
	return o
}

// SetLastUpdated adds the lastUpdated to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetLastUpdated(lastUpdated *string) {
	o.LastUpdated = lastUpdated
}

// WithLastUpdatedGt adds the lastUpdatedGt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithLastUpdatedGt(lastUpdatedGt *string) *CircuitsProviderAccountsListParams {
	o.SetLastUpdatedGt(lastUpdatedGt)
	return o
}

// SetLastUpdatedGt adds the lastUpdatedGt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetLastUpdatedGt(lastUpdatedGt *string) {
	o.LastUpdatedGt = lastUpdatedGt
}

// WithLastUpdatedGte adds the lastUpdatedGte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithLastUpdatedGte(lastUpdatedGte *string) *CircuitsProviderAccountsListParams {
	o.SetLastUpdatedGte(lastUpdatedGte)
	return o
}

// SetLastUpdatedGte adds the lastUpdatedGte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetLastUpdatedGte(lastUpdatedGte *string) {
	o.LastUpdatedGte = lastUpdatedGte
}

// WithLastUpdatedLt adds the lastUpdatedLt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithLastUpdatedLt(lastUpdatedLt *string) *CircuitsProviderAccountsListParams {
	o.SetLastUpdatedLt(lastUpdatedLt)
	return o
}

// SetLastUpdatedLt adds the lastUpdatedLt to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetLastUpdatedLt(lastUpdatedLt *string) {
	o.LastUpdatedLt = lastUpdatedLt
}

// WithLastUpdatedLte adds the lastUpdatedLte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithLastUpdatedLte(lastUpdatedLte *string) *CircuitsProviderAccountsListParams {
	o.SetLastUpdatedLte(lastUpdatedLte)
	return o
}

// SetLastUpdatedLte adds the lastUpdatedLte to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetLastUpdatedLte(lastUpdatedLte *string) {
	o.LastUpdatedLte = lastUpdatedLte
}

// WithLastUpdatedn adds the lastUpdatedn to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithLastUpdatedn(lastUpdatedn *string) *CircuitsProviderAccountsListParams {
	o.SetLastUpdatedn(lastUpdatedn)
	return o
}

// SetLastUpdatedn adds the lastUpdatedN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetLastUpdatedn(lastUpdatedn *string) {
	o.LastUpdatedn = lastUpdatedn
}

// WithLimit adds the limit to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithLimit(limit *int64) *CircuitsProviderAccountsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithName(name *string) *CircuitsProviderAccountsListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetName(name *string) {
	o.Name = name
}

// WithNameEmpty adds the nameEmpty to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameEmpty(nameEmpty *string) *CircuitsProviderAccountsListParams {
	o.SetNameEmpty(nameEmpty)
	return o
}

// SetNameEmpty adds the nameEmpty to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameEmpty(nameEmpty *string) {
	o.NameEmpty = nameEmpty
}

// WithNameIc adds the nameIc to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameIc(nameIc *string) *CircuitsProviderAccountsListParams {
	o.SetNameIc(nameIc)
	return o
}

// SetNameIc adds the nameIc to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameIc(nameIc *string) {
	o.NameIc = nameIc
}

// WithNameIe adds the nameIe to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameIe(nameIe *string) *CircuitsProviderAccountsListParams {
	o.SetNameIe(nameIe)
	return o
}

// SetNameIe adds the nameIe to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameIe(nameIe *string) {
	o.NameIe = nameIe
}

// WithNameIew adds the nameIew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameIew(nameIew *string) *CircuitsProviderAccountsListParams {
	o.SetNameIew(nameIew)
	return o
}

// SetNameIew adds the nameIew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameIew(nameIew *string) {
	o.NameIew = nameIew
}

// WithNameIsw adds the nameIsw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameIsw(nameIsw *string) *CircuitsProviderAccountsListParams {
	o.SetNameIsw(nameIsw)
	return o
}

// SetNameIsw adds the nameIsw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameIsw(nameIsw *string) {
	o.NameIsw = nameIsw
}

// WithNamen adds the namen to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNamen(namen *string) *CircuitsProviderAccountsListParams {
	o.SetNamen(namen)
	return o
}

// SetNamen adds the nameN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNamen(namen *string) {
	o.Namen = namen
}

// WithNameNic adds the nameNic to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameNic(nameNic *string) *CircuitsProviderAccountsListParams {
	o.SetNameNic(nameNic)
	return o
}

// SetNameNic adds the nameNic to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameNic(nameNic *string) {
	o.NameNic = nameNic
}

// WithNameNie adds the nameNie to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameNie(nameNie *string) *CircuitsProviderAccountsListParams {
	o.SetNameNie(nameNie)
	return o
}

// SetNameNie adds the nameNie to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameNie(nameNie *string) {
	o.NameNie = nameNie
}

// WithNameNiew adds the nameNiew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameNiew(nameNiew *string) *CircuitsProviderAccountsListParams {
	o.SetNameNiew(nameNiew)
	return o
}

// SetNameNiew adds the nameNiew to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameNiew(nameNiew *string) {
	o.NameNiew = nameNiew
}

// WithNameNisw adds the nameNisw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithNameNisw(nameNisw *string) *CircuitsProviderAccountsListParams {
	o.SetNameNisw(nameNisw)
	return o
}

// SetNameNisw adds the nameNisw to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetNameNisw(nameNisw *string) {
	o.NameNisw = nameNisw
}

// WithOffset adds the offset to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithOffset(offset *int64) *CircuitsProviderAccountsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithOrdering(ordering *string) *CircuitsProviderAccountsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithProvider adds the provider to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithProvider(provider *string) *CircuitsProviderAccountsListParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetProvider(provider *string) {
	o.Provider = provider
}

// WithProvidern adds the providern to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithProvidern(providern *string) *CircuitsProviderAccountsListParams {
	o.SetProvidern(providern)
	return o
}

// SetProvidern adds the providerN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetProvidern(providern *string) {
	o.Providern = providern
}

// WithProviderID adds the providerID to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithProviderID(providerID *string) *CircuitsProviderAccountsListParams {
	o.SetProviderID(providerID)
	return o
}

// SetProviderID adds the providerId to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetProviderID(providerID *string) {
	o.ProviderID = providerID
}

// WithProviderIDn adds the providerIDn to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithProviderIDn(providerIDn *string) *CircuitsProviderAccountsListParams {
	o.SetProviderIDn(providerIDn)
	return o
}

// SetProviderIDn adds the providerIdN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetProviderIDn(providerIDn *string) {
	o.ProviderIDn = providerIDn
}

// WithQ adds the q to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithQ(q *string) *CircuitsProviderAccountsListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetQ(q *string) {
	o.Q = q
}

// WithTag adds the tag to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithTag(tag *string) *CircuitsProviderAccountsListParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetTag(tag *string) {
	o.Tag = tag
}

// WithTagn adds the tagn to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithTagn(tagn *string) *CircuitsProviderAccountsListParams {
	o.SetTagn(tagn)
	return o
}

// SetTagn adds the tagN to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetTagn(tagn *string) {
	o.Tagn = tagn
}

// WithUpdatedByRequest adds the updatedByRequest to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) WithUpdatedByRequest(updatedByRequest *string) *CircuitsProviderAccountsListParams {
	o.SetUpdatedByRequest(updatedByRequest)
	return o
}

// SetUpdatedByRequest adds the updatedByRequest to the circuits provider accounts list params
func (o *CircuitsProviderAccountsListParams) SetUpdatedByRequest(updatedByRequest *string) {
	o.UpdatedByRequest = updatedByRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CircuitsProviderAccountsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Account != nil {

		// query param account
		var qrAccount string

		if o.Account != nil {
			qrAccount = *o.Account
		}
		qAccount := qrAccount
		if qAccount != "" {

			if err := r.SetQueryParam("account", qAccount); err != nil {
				return err
			}
		}
	}

	if o.AccountEmpty != nil {

		// query param account__empty
		var qrAccountEmpty string

		if o.AccountEmpty != nil {
			qrAccountEmpty = *o.AccountEmpty
		}
		qAccountEmpty := qrAccountEmpty
		if qAccountEmpty != "" {

			if err := r.SetQueryParam("account__empty", qAccountEmpty); err != nil {
				return err
			}
		}
	}

	if o.AccountIc != nil {

		// query param account__ic
		var qrAccountIc string

		if o.AccountIc != nil {
			qrAccountIc = *o.AccountIc
		}
		qAccountIc := qrAccountIc
		if qAccountIc != "" {

			if err := r.SetQueryParam("account__ic", qAccountIc); err != nil {
				return err
			}
		}
	}

	if o.AccountIe != nil {

		// query param account__ie
		var qrAccountIe string

		if o.AccountIe != nil {
			qrAccountIe = *o.AccountIe
		}
		qAccountIe := qrAccountIe
		if qAccountIe != "" {

			if err := r.SetQueryParam("account__ie", qAccountIe); err != nil {
				return err
			}
		}
	}

	if o.AccountIew != nil {

		// query param account__iew
		var qrAccountIew string

		if o.AccountIew != nil {
			qrAccountIew = *o.AccountIew
		}
		qAccountIew := qrAccountIew
		if qAccountIew != "" {

			if err := r.SetQueryParam("account__iew", qAccountIew); err != nil {
				return err
			}
		}
	}

	if o.AccountIsw != nil {

		// query param account__isw
		var qrAccountIsw string

		if o.AccountIsw != nil {
			qrAccountIsw = *o.AccountIsw
		}
		qAccountIsw := qrAccountIsw
		if qAccountIsw != "" {

			if err := r.SetQueryParam("account__isw", qAccountIsw); err != nil {
				return err
			}
		}
	}

	if o.Accountn != nil {

		// query param account__n
		var qrAccountn string

		if o.Accountn != nil {
			qrAccountn = *o.Accountn
		}
		qAccountn := qrAccountn
		if qAccountn != "" {

			if err := r.SetQueryParam("account__n", qAccountn); err != nil {
				return err
			}
		}
	}

	if o.AccountNic != nil {

		// query param account__nic
		var qrAccountNic string

		if o.AccountNic != nil {
			qrAccountNic = *o.AccountNic
		}
		qAccountNic := qrAccountNic
		if qAccountNic != "" {

			if err := r.SetQueryParam("account__nic", qAccountNic); err != nil {
				return err
			}
		}
	}

	if o.AccountNie != nil {

		// query param account__nie
		var qrAccountNie string

		if o.AccountNie != nil {
			qrAccountNie = *o.AccountNie
		}
		qAccountNie := qrAccountNie
		if qAccountNie != "" {

			if err := r.SetQueryParam("account__nie", qAccountNie); err != nil {
				return err
			}
		}
	}

	if o.AccountNiew != nil {

		// query param account__niew
		var qrAccountNiew string

		if o.AccountNiew != nil {
			qrAccountNiew = *o.AccountNiew
		}
		qAccountNiew := qrAccountNiew
		if qAccountNiew != "" {

			if err := r.SetQueryParam("account__niew", qAccountNiew); err != nil {
				return err
			}
		}
	}

	if o.AccountNisw != nil {

		// query param account__nisw
		var qrAccountNisw string

		if o.AccountNisw != nil {
			qrAccountNisw = *o.AccountNisw
		}
		qAccountNisw := qrAccountNisw
		if qAccountNisw != "" {

			if err := r.SetQueryParam("account__nisw", qAccountNisw); err != nil {
				return err
			}
		}
	}

	if o.Created != nil {

		// query param created
		var qrCreated string

		if o.Created != nil {
			qrCreated = *o.Created
		}
		qCreated := qrCreated
		if qCreated != "" {

			if err := r.SetQueryParam("created", qCreated); err != nil {
				return err
			}
		}
	}

	if o.CreatedGt != nil {

		// query param created__gt
		var qrCreatedGt string

		if o.CreatedGt != nil {
			qrCreatedGt = *o.CreatedGt
		}
		qCreatedGt := qrCreatedGt
		if qCreatedGt != "" {

			if err := r.SetQueryParam("created__gt", qCreatedGt); err != nil {
				return err
			}
		}
	}

	if o.CreatedGte != nil {

		// query param created__gte
		var qrCreatedGte string

		if o.CreatedGte != nil {
			qrCreatedGte = *o.CreatedGte
		}
		qCreatedGte := qrCreatedGte
		if qCreatedGte != "" {

			if err := r.SetQueryParam("created__gte", qCreatedGte); err != nil {
				return err
			}
		}
	}

	if o.CreatedLt != nil {

		// query param created__lt
		var qrCreatedLt string

		if o.CreatedLt != nil {
			qrCreatedLt = *o.CreatedLt
		}
		qCreatedLt := qrCreatedLt
		if qCreatedLt != "" {

			if err := r.SetQueryParam("created__lt", qCreatedLt); err != nil {
				return err
			}
		}
	}

	if o.CreatedLte != nil {

		// query param created__lte
		var qrCreatedLte string

		if o.CreatedLte != nil {
			qrCreatedLte = *o.CreatedLte
		}
		qCreatedLte := qrCreatedLte
		if qCreatedLte != "" {

			if err := r.SetQueryParam("created__lte", qCreatedLte); err != nil {
				return err
			}
		}
	}

	if o.Createdn != nil {

		// query param created__n
		var qrCreatedn string

		if o.Createdn != nil {
			qrCreatedn = *o.Createdn
		}
		qCreatedn := qrCreatedn
		if qCreatedn != "" {

			if err := r.SetQueryParam("created__n", qCreatedn); err != nil {
				return err
			}
		}
	}

	if o.CreatedByRequest != nil {

		// query param created_by_request
		var qrCreatedByRequest string

		if o.CreatedByRequest != nil {
			qrCreatedByRequest = *o.CreatedByRequest
		}
		qCreatedByRequest := qrCreatedByRequest
		if qCreatedByRequest != "" {

			if err := r.SetQueryParam("created_by_request", qCreatedByRequest); err != nil {
				return err
			}
		}
	}

	if o.Description != nil {

		// query param description
		var qrDescription string

		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {

			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}
	}

	if o.DescriptionEmpty != nil {

		// query param description__empty
		var qrDescriptionEmpty string

		if o.DescriptionEmpty != nil {
			qrDescriptionEmpty = *o.DescriptionEmpty
		}
		qDescriptionEmpty := qrDescriptionEmpty
		if qDescriptionEmpty != "" {

			if err := r.SetQueryParam("description__empty", qDescriptionEmpty); err != nil {
				return err
			}
		}
	}

	if o.DescriptionIc != nil {

		// query param description__ic
		var qrDescriptionIc string

		if o.DescriptionIc != nil {
			qrDescriptionIc = *o.DescriptionIc
		}
		qDescriptionIc := qrDescriptionIc
		if qDescriptionIc != "" {

			if err := r.SetQueryParam("description__ic", qDescriptionIc); err != nil {
				return err
			}
		}
	}

	if o.DescriptionIe != nil {

		// query param description__ie
		var qrDescriptionIe string

		if o.DescriptionIe != nil {
			qrDescriptionIe = *o.DescriptionIe
		}
		qDescriptionIe := qrDescriptionIe
		if qDescriptionIe != "" {

			if err := r.SetQueryParam("description__ie", qDescriptionIe); err != nil {
				return err
			}
		}
	}

	if o.DescriptionIew != nil {

		// query param description__iew
		var qrDescriptionIew string

		if o.DescriptionIew != nil {
			qrDescriptionIew = *o.DescriptionIew
		}
		qDescriptionIew := qrDescriptionIew
		if qDescriptionIew != "" {

			if err := r.SetQueryParam("description__iew", qDescriptionIew); err != nil {
				return err
			}
		}
	}

	if o.DescriptionIsw != nil {

		// query param description__isw
		var qrDescriptionIsw string

		if o.DescriptionIsw != nil {
			qrDescriptionIsw = *o.DescriptionIsw
		}
		qDescriptionIsw := qrDescriptionIsw
		if qDescriptionIsw != "" {

			if err := r.SetQueryParam("description__isw", qDescriptionIsw); err != nil {
				return err
			}
		}
	}

	if o.Descriptionn != nil {

		// query param description__n
		var qrDescriptionn string

		if o.Descriptionn != nil {
			qrDescriptionn = *o.Descriptionn
		}
		qDescriptionn := qrDescriptionn
		if qDescriptionn != "" {

			if err := r.SetQueryParam("description__n", qDescriptionn); err != nil {
				return err
			}
		}
	}

	if o.DescriptionNic != nil {

		// query param description__nic
		var qrDescriptionNic string

		if o.DescriptionNic != nil {
			qrDescriptionNic = *o.DescriptionNic
		}
		qDescriptionNic := qrDescriptionNic
		if qDescriptionNic != "" {

			if err := r.SetQueryParam("description__nic", qDescriptionNic); err != nil {
				return err
			}
		}
	}

	if o.DescriptionNie != nil {

		// query param description__nie
		var qrDescriptionNie string

		if o.DescriptionNie != nil {
			qrDescriptionNie = *o.DescriptionNie
		}
		qDescriptionNie := qrDescriptionNie
		if qDescriptionNie != "" {

			if err := r.SetQueryParam("description__nie", qDescriptionNie); err != nil {
				return err
			}
		}
	}

	if o.DescriptionNiew != nil {

		// query param description__niew
		var qrDescriptionNiew string

		if o.DescriptionNiew != nil {
			qrDescriptionNiew = *o.DescriptionNiew
		}
		qDescriptionNiew := qrDescriptionNiew
		if qDescriptionNiew != "" {

			if err := r.SetQueryParam("description__niew", qDescriptionNiew); err != nil {
				return err
			}
		}
	}

	if o.DescriptionNisw != nil {

		// query param description__nisw
		var qrDescriptionNisw string

		if o.DescriptionNisw != nil {
			qrDescriptionNisw = *o.DescriptionNisw
		}
		qDescriptionNisw := qrDescriptionNisw
		if qDescriptionNisw != "" {

			if err := r.SetQueryParam("description__nisw", qDescriptionNisw); err != nil {
				return err
			}
		}
	}

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.IDGt != nil {

		// query param id__gt
		var qrIDGt string

		if o.IDGt != nil {
			qrIDGt = *o.IDGt
		}
		qIDGt := qrIDGt
		if qIDGt != "" {

			if err := r.SetQueryParam("id__gt", qIDGt); err != nil {
				return err
			}
		}
	}

	if o.IDGte != nil {

		// query param id__gte
		var qrIDGte string

		if o.IDGte != nil {
			qrIDGte = *o.IDGte
		}
		qIDGte := qrIDGte
		if qIDGte != "" {

			if err := r.SetQueryParam("id__gte", qIDGte); err != nil {
				return err
			}
		}
	}

	if o.IDLt != nil {

		// query param id__lt
		var qrIDLt string

		if o.IDLt != nil {
			qrIDLt = *o.IDLt
		}
		qIDLt := qrIDLt
		if qIDLt != "" {

			if err := r.SetQueryParam("id__lt", qIDLt); err != nil {
				return err
			}
		}
	}

	if o.IDLte != nil {

		// query param id__lte
		var qrIDLte string

		if o.IDLte != nil {
			qrIDLte = *o.IDLte
		}
		qIDLte := qrIDLte
		if qIDLte != "" {

			if err := r.SetQueryParam("id__lte", qIDLte); err != nil {
				return err
			}
		}
	}

	if o.IDn != nil {

		// query param id__n
		var qrIDn string

		if o.IDn != nil {
			qrIDn = *o.IDn
		}
		qIDn := qrIDn
		if qIDn != "" {

			if err := r.SetQueryParam("id__n", qIDn); err != nil {
				return err
			}
		}
	}

	if o.LastUpdated != nil {

		// query param last_updated
		var qrLastUpdated string

		if o.LastUpdated != nil {
			qrLastUpdated = *o.LastUpdated
		}
		qLastUpdated := qrLastUpdated
		if qLastUpdated != "" {

			if err := r.SetQueryParam("last_updated", qLastUpdated); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedGt != nil {

		// query param last_updated__gt
		var qrLastUpdatedGt string

		if o.LastUpdatedGt != nil {
			qrLastUpdatedGt = *o.LastUpdatedGt
		}
		qLastUpdatedGt := qrLastUpdatedGt
		if qLastUpdatedGt != "" {

			if err := r.SetQueryParam("last_updated__gt", qLastUpdatedGt); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedGte != nil {

		// query param last_updated__gte
		var qrLastUpdatedGte string

		if o.LastUpdatedGte != nil {
			qrLastUpdatedGte = *o.LastUpdatedGte
		}
		qLastUpdatedGte := qrLastUpdatedGte
		if qLastUpdatedGte != "" {

			if err := r.SetQueryParam("last_updated__gte", qLastUpdatedGte); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedLt != nil {

		// query param last_updated__lt
		var qrLastUpdatedLt string

		if o.LastUpdatedLt != nil {
			qrLastUpdatedLt = *o.LastUpdatedLt
		}
		qLastUpdatedLt := qrLastUpdatedLt
		if qLastUpdatedLt != "" {

			if err := r.SetQueryParam("last_updated__lt", qLastUpdatedLt); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedLte != nil {

		// query param last_updated__lte
		var qrLastUpdatedLte string

		if o.LastUpdatedLte != nil {
			qrLastUpdatedLte = *o.LastUpdatedLte
		}
		qLastUpdatedLte := qrLastUpdatedLte
		if qLastUpdatedLte != "" {

			if err := r.SetQueryParam("last_updated__lte", qLastUpdatedLte); err != nil {
				return err
			}
		}
	}

	if o.LastUpdatedn != nil {

		// query param last_updated__n
		var qrLastUpdatedn string

		if o.LastUpdatedn != nil {
			qrLastUpdatedn = *o.LastUpdatedn
		}
		qLastUpdatedn := qrLastUpdatedn
		if qLastUpdatedn != "" {

			if err := r.SetQueryParam("last_updated__n", qLastUpdatedn); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.NameEmpty != nil {

		// query param name__empty
		var qrNameEmpty string

		if o.NameEmpty != nil {
			qrNameEmpty = *o.NameEmpty
		}
		qNameEmpty := qrNameEmpty
		if qNameEmpty != "" {

			if err := r.SetQueryParam("name__empty", qNameEmpty); err != nil {
				return err
			}
		}
	}

	if o.NameIc != nil {

		// query param name__ic
		var qrNameIc string

		if o.NameIc != nil {
			qrNameIc = *o.NameIc
		}
		qNameIc := qrNameIc
		if qNameIc != "" {

			if err := r.SetQueryParam("name__ic", qNameIc); err != nil {
				return err
			}
		}
	}

	if o.NameIe != nil {

		// query param name__ie
		var qrNameIe string

		if o.NameIe != nil {
			qrNameIe = *o.NameIe
		}
		qNameIe := qrNameIe
		if qNameIe != "" {

			if err := r.SetQueryParam("name__ie", qNameIe); err != nil {
				return err
			}
		}
	}

	if o.NameIew != nil {

		// query param name__iew
		var qrNameIew string

		if o.NameIew != nil {
			qrNameIew = *o.NameIew
		}
		qNameIew := qrNameIew
		if qNameIew != "" {

			if err := r.SetQueryParam("name__iew", qNameIew); err != nil {
				return err
			}
		}
	}

	if o.NameIsw != nil {

		// query param name__isw
		var qrNameIsw string

		if o.NameIsw != nil {
			qrNameIsw = *o.NameIsw
		}
		qNameIsw := qrNameIsw
		if qNameIsw != "" {

			if err := r.SetQueryParam("name__isw", qNameIsw); err != nil {
				return err
			}
		}
	}

	if o.Namen != nil {

		// query param name__n
		var qrNamen string

		if o.Namen != nil {
			qrNamen = *o.Namen
		}
		qNamen := qrNamen
		if qNamen != "" {

			if err := r.SetQueryParam("name__n", qNamen); err != nil {
				return err
			}
		}
	}

	if o.NameNic != nil {

		// query param name__nic
		var qrNameNic string

		if o.NameNic != nil {
			qrNameNic = *o.NameNic
		}
		qNameNic := qrNameNic
		if qNameNic != "" {

			if err := r.SetQueryParam("name__nic", qNameNic); err != nil {
				return err
			}
		}
	}

	if o.NameNie != nil {

		// query param name__nie
		var qrNameNie string

		if o.NameNie != nil {
			qrNameNie = *o.NameNie
		}
		qNameNie := qrNameNie
		if qNameNie != "" {

			if err := r.SetQueryParam("name__nie", qNameNie); err != nil {
				return err
			}
		}
	}

	if o.NameNiew != nil {

		// query param name__niew
		var qrNameNiew string

		if o.NameNiew != nil {
			qrNameNiew = *o.NameNiew
		}
		qNameNiew := qrNameNiew
		if qNameNiew != "" {

			if err := r.SetQueryParam("name__niew", qNameNiew); err != nil {
				return err
			}
		}
	}

	if o.NameNisw != nil {

		// query param name__nisw
		var qrNameNisw string

		if o.NameNisw != nil {
			qrNameNisw = *o.NameNisw
		}
		qNameNisw := qrNameNisw
		if qNameNisw != "" {

			if err := r.SetQueryParam("name__nisw", qNameNisw); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string

		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {

			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}
	}

	if o.Provider != nil {

		// query param provider
		var qrProvider string

		if o.Provider != nil {
			qrProvider = *o.Provider
		}
		qProvider := qrProvider
		if qProvider != "" {

			if err := r.SetQueryParam("provider", qProvider); err != nil {
				return err
			}
		}
	}

	if o.Providern != nil {

		// query param provider__n
		var qrProvidern string

		if o.Providern != nil {
			qrProvidern = *o.Providern
		}
		qProvidern := qrProvidern
		if qProvidern != "" {

			if err := r.SetQueryParam("provider__n", qProvidern); err != nil {
				return err
			}
		}
	}

	if o.ProviderID != nil {

		// query param provider_id
		var qrProviderID string

		if o.ProviderID != nil {
			qrProviderID = *o.ProviderID
		}
		qProviderID := qrProviderID
		if qProviderID != "" {

			if err := r.SetQueryParam("provider_id", qProviderID); err != nil {
				return err
			}
		}
	}

	if o.ProviderIDn != nil {

		// query param provider_id__n
		var qrProviderIDn string

		if o.ProviderIDn != nil {
			qrProviderIDn = *o.ProviderIDn
		}
		qProviderIDn := qrProviderIDn
		if qProviderIDn != "" {

			if err := r.SetQueryParam("provider_id__n", qProviderIDn); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.Tag != nil {

		// query param tag
		var qrTag string

		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {

			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}
	}

	if o.Tagn != nil {

		// query param tag__n
		var qrTagn string

		if o.Tagn != nil {
			qrTagn = *o.Tagn
		}
		qTagn := qrTagn
		if qTagn != "" {

			if err := r.SetQueryParam("tag__n", qTagn); err != nil {
				return err
			}
		}
	}

	if o.UpdatedByRequest != nil {

		// query param updated_by_request
		var qrUpdatedByRequest string

		if o.UpdatedByRequest != nil {
			qrUpdatedByRequest = *o.UpdatedByRequest
		}
		qUpdatedByRequest := qrUpdatedByRequest
		if qUpdatedByRequest != "" {

			if err := r.SetQueryParam("updated_by_request", qUpdatedByRequest); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
