// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamVrfsCreateReader is a Reader for the IpamVrfsCreate structure.
type IpamVrfsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamVrfsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIpamVrfsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamVrfsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamVrfsCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamVrfsCreateCreated creates a IpamVrfsCreateCreated with default headers values
func NewIpamVrfsCreateCreated() *IpamVrfsCreateCreated {
	return &IpamVrfsCreateCreated{}
}

/*
IpamVrfsCreateCreated describes a response with status code 201, with default header values.

IpamVrfsCreateCreated ipam vrfs create created
*/
type IpamVrfsCreateCreated struct {
	Payload *models.VRF
}

// IsSuccess returns true when this ipam vrfs create created response has a 2xx status code
func (o *IpamVrfsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam vrfs create created response has a 3xx status code
func (o *IpamVrfsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vrfs create created response has a 4xx status code
func (o *IpamVrfsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam vrfs create created response has a 5xx status code
func (o *IpamVrfsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vrfs create created response a status code equal to that given
func (o *IpamVrfsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *IpamVrfsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/vrfs/][%d] ipamVrfsCreateCreated  %+v", 201, o.Payload)
}

func (o *IpamVrfsCreateCreated) String() string {
	return fmt.Sprintf("[POST /ipam/vrfs/][%d] ipamVrfsCreateCreated  %+v", 201, o.Payload)
}

func (o *IpamVrfsCreateCreated) GetPayload() *models.VRF {
	return o.Payload
}

func (o *IpamVrfsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VRF)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamVrfsCreateBadRequest creates a IpamVrfsCreateBadRequest with default headers values
func NewIpamVrfsCreateBadRequest() *IpamVrfsCreateBadRequest {
	return &IpamVrfsCreateBadRequest{}
}

/*
IpamVrfsCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamVrfsCreateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam vrfs create bad request response has a 2xx status code
func (o *IpamVrfsCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam vrfs create bad request response has a 3xx status code
func (o *IpamVrfsCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vrfs create bad request response has a 4xx status code
func (o *IpamVrfsCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam vrfs create bad request response has a 5xx status code
func (o *IpamVrfsCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vrfs create bad request response a status code equal to that given
func (o *IpamVrfsCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamVrfsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /ipam/vrfs/][%d] ipamVrfsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamVrfsCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /ipam/vrfs/][%d] ipamVrfsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamVrfsCreateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamVrfsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamVrfsCreateDefault creates a IpamVrfsCreateDefault with default headers values
func NewIpamVrfsCreateDefault(code int) *IpamVrfsCreateDefault {
	return &IpamVrfsCreateDefault{
		_statusCode: code,
	}
}

/*
IpamVrfsCreateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamVrfsCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam vrfs create default response
func (o *IpamVrfsCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam vrfs create default response has a 2xx status code
func (o *IpamVrfsCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam vrfs create default response has a 3xx status code
func (o *IpamVrfsCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam vrfs create default response has a 4xx status code
func (o *IpamVrfsCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam vrfs create default response has a 5xx status code
func (o *IpamVrfsCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam vrfs create default response a status code equal to that given
func (o *IpamVrfsCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamVrfsCreateDefault) Error() string {
	return fmt.Sprintf("[POST /ipam/vrfs/][%d] ipam_vrfs_create default  %+v", o._statusCode, o.Payload)
}

func (o *IpamVrfsCreateDefault) String() string {
	return fmt.Sprintf("[POST /ipam/vrfs/][%d] ipam_vrfs_create default  %+v", o._statusCode, o.Payload)
}

func (o *IpamVrfsCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamVrfsCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
