// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamRirsBulkPartialUpdateReader is a Reader for the IpamRirsBulkPartialUpdate structure.
type IpamRirsBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamRirsBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamRirsBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamRirsBulkPartialUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamRirsBulkPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamRirsBulkPartialUpdateOK creates a IpamRirsBulkPartialUpdateOK with default headers values
func NewIpamRirsBulkPartialUpdateOK() *IpamRirsBulkPartialUpdateOK {
	return &IpamRirsBulkPartialUpdateOK{}
}

/*
IpamRirsBulkPartialUpdateOK describes a response with status code 200, with default header values.

IpamRirsBulkPartialUpdateOK ipam rirs bulk partial update o k
*/
type IpamRirsBulkPartialUpdateOK struct {
	Payload *models.RIR
}

// IsSuccess returns true when this ipam rirs bulk partial update o k response has a 2xx status code
func (o *IpamRirsBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam rirs bulk partial update o k response has a 3xx status code
func (o *IpamRirsBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam rirs bulk partial update o k response has a 4xx status code
func (o *IpamRirsBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam rirs bulk partial update o k response has a 5xx status code
func (o *IpamRirsBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam rirs bulk partial update o k response a status code equal to that given
func (o *IpamRirsBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *IpamRirsBulkPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /ipam/rirs/][%d] ipamRirsBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamRirsBulkPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /ipam/rirs/][%d] ipamRirsBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamRirsBulkPartialUpdateOK) GetPayload() *models.RIR {
	return o.Payload
}

func (o *IpamRirsBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RIR)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamRirsBulkPartialUpdateBadRequest creates a IpamRirsBulkPartialUpdateBadRequest with default headers values
func NewIpamRirsBulkPartialUpdateBadRequest() *IpamRirsBulkPartialUpdateBadRequest {
	return &IpamRirsBulkPartialUpdateBadRequest{}
}

/*
IpamRirsBulkPartialUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamRirsBulkPartialUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam rirs bulk partial update bad request response has a 2xx status code
func (o *IpamRirsBulkPartialUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam rirs bulk partial update bad request response has a 3xx status code
func (o *IpamRirsBulkPartialUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam rirs bulk partial update bad request response has a 4xx status code
func (o *IpamRirsBulkPartialUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam rirs bulk partial update bad request response has a 5xx status code
func (o *IpamRirsBulkPartialUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam rirs bulk partial update bad request response a status code equal to that given
func (o *IpamRirsBulkPartialUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamRirsBulkPartialUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /ipam/rirs/][%d] ipamRirsBulkPartialUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamRirsBulkPartialUpdateBadRequest) String() string {
	return fmt.Sprintf("[PATCH /ipam/rirs/][%d] ipamRirsBulkPartialUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamRirsBulkPartialUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamRirsBulkPartialUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamRirsBulkPartialUpdateDefault creates a IpamRirsBulkPartialUpdateDefault with default headers values
func NewIpamRirsBulkPartialUpdateDefault(code int) *IpamRirsBulkPartialUpdateDefault {
	return &IpamRirsBulkPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
IpamRirsBulkPartialUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamRirsBulkPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam rirs bulk partial update default response
func (o *IpamRirsBulkPartialUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam rirs bulk partial update default response has a 2xx status code
func (o *IpamRirsBulkPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam rirs bulk partial update default response has a 3xx status code
func (o *IpamRirsBulkPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam rirs bulk partial update default response has a 4xx status code
func (o *IpamRirsBulkPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam rirs bulk partial update default response has a 5xx status code
func (o *IpamRirsBulkPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam rirs bulk partial update default response a status code equal to that given
func (o *IpamRirsBulkPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamRirsBulkPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /ipam/rirs/][%d] ipam_rirs_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *IpamRirsBulkPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /ipam/rirs/][%d] ipam_rirs_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *IpamRirsBulkPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamRirsBulkPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
