// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamL2vpnTerminationsBulkUpdateReader is a Reader for the IpamL2vpnTerminationsBulkUpdate structure.
type IpamL2vpnTerminationsBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamL2vpnTerminationsBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamL2vpnTerminationsBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamL2vpnTerminationsBulkUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamL2vpnTerminationsBulkUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamL2vpnTerminationsBulkUpdateOK creates a IpamL2vpnTerminationsBulkUpdateOK with default headers values
func NewIpamL2vpnTerminationsBulkUpdateOK() *IpamL2vpnTerminationsBulkUpdateOK {
	return &IpamL2vpnTerminationsBulkUpdateOK{}
}

/*
IpamL2vpnTerminationsBulkUpdateOK describes a response with status code 200, with default header values.

IpamL2vpnTerminationsBulkUpdateOK ipam l2vpn terminations bulk update o k
*/
type IpamL2vpnTerminationsBulkUpdateOK struct {
	Payload *models.L2VPNTermination
}

// IsSuccess returns true when this ipam l2vpn terminations bulk update o k response has a 2xx status code
func (o *IpamL2vpnTerminationsBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam l2vpn terminations bulk update o k response has a 3xx status code
func (o *IpamL2vpnTerminationsBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam l2vpn terminations bulk update o k response has a 4xx status code
func (o *IpamL2vpnTerminationsBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam l2vpn terminations bulk update o k response has a 5xx status code
func (o *IpamL2vpnTerminationsBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam l2vpn terminations bulk update o k response a status code equal to that given
func (o *IpamL2vpnTerminationsBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *IpamL2vpnTerminationsBulkUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /ipam/l2vpn-terminations/][%d] ipamL2vpnTerminationsBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamL2vpnTerminationsBulkUpdateOK) String() string {
	return fmt.Sprintf("[PUT /ipam/l2vpn-terminations/][%d] ipamL2vpnTerminationsBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamL2vpnTerminationsBulkUpdateOK) GetPayload() *models.L2VPNTermination {
	return o.Payload
}

func (o *IpamL2vpnTerminationsBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.L2VPNTermination)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamL2vpnTerminationsBulkUpdateBadRequest creates a IpamL2vpnTerminationsBulkUpdateBadRequest with default headers values
func NewIpamL2vpnTerminationsBulkUpdateBadRequest() *IpamL2vpnTerminationsBulkUpdateBadRequest {
	return &IpamL2vpnTerminationsBulkUpdateBadRequest{}
}

/*
IpamL2vpnTerminationsBulkUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamL2vpnTerminationsBulkUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam l2vpn terminations bulk update bad request response has a 2xx status code
func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam l2vpn terminations bulk update bad request response has a 3xx status code
func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam l2vpn terminations bulk update bad request response has a 4xx status code
func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam l2vpn terminations bulk update bad request response has a 5xx status code
func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam l2vpn terminations bulk update bad request response a status code equal to that given
func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /ipam/l2vpn-terminations/][%d] ipamL2vpnTerminationsBulkUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /ipam/l2vpn-terminations/][%d] ipamL2vpnTerminationsBulkUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamL2vpnTerminationsBulkUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamL2vpnTerminationsBulkUpdateDefault creates a IpamL2vpnTerminationsBulkUpdateDefault with default headers values
func NewIpamL2vpnTerminationsBulkUpdateDefault(code int) *IpamL2vpnTerminationsBulkUpdateDefault {
	return &IpamL2vpnTerminationsBulkUpdateDefault{
		_statusCode: code,
	}
}

/*
IpamL2vpnTerminationsBulkUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamL2vpnTerminationsBulkUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam l2vpn terminations bulk update default response
func (o *IpamL2vpnTerminationsBulkUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam l2vpn terminations bulk update default response has a 2xx status code
func (o *IpamL2vpnTerminationsBulkUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam l2vpn terminations bulk update default response has a 3xx status code
func (o *IpamL2vpnTerminationsBulkUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam l2vpn terminations bulk update default response has a 4xx status code
func (o *IpamL2vpnTerminationsBulkUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam l2vpn terminations bulk update default response has a 5xx status code
func (o *IpamL2vpnTerminationsBulkUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam l2vpn terminations bulk update default response a status code equal to that given
func (o *IpamL2vpnTerminationsBulkUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamL2vpnTerminationsBulkUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /ipam/l2vpn-terminations/][%d] ipam_l2vpn-terminations_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *IpamL2vpnTerminationsBulkUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /ipam/l2vpn-terminations/][%d] ipam_l2vpn-terminations_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *IpamL2vpnTerminationsBulkUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamL2vpnTerminationsBulkUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
