// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamVlanGroupsCreateReader is a Reader for the IpamVlanGroupsCreate structure.
type IpamVlanGroupsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamVlanGroupsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIpamVlanGroupsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamVlanGroupsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamVlanGroupsCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamVlanGroupsCreateCreated creates a IpamVlanGroupsCreateCreated with default headers values
func NewIpamVlanGroupsCreateCreated() *IpamVlanGroupsCreateCreated {
	return &IpamVlanGroupsCreateCreated{}
}

/*
IpamVlanGroupsCreateCreated describes a response with status code 201, with default header values.

IpamVlanGroupsCreateCreated ipam vlan groups create created
*/
type IpamVlanGroupsCreateCreated struct {
	Payload *models.VLANGroup
}

// IsSuccess returns true when this ipam vlan groups create created response has a 2xx status code
func (o *IpamVlanGroupsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam vlan groups create created response has a 3xx status code
func (o *IpamVlanGroupsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vlan groups create created response has a 4xx status code
func (o *IpamVlanGroupsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam vlan groups create created response has a 5xx status code
func (o *IpamVlanGroupsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vlan groups create created response a status code equal to that given
func (o *IpamVlanGroupsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *IpamVlanGroupsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/vlan-groups/][%d] ipamVlanGroupsCreateCreated  %+v", 201, o.Payload)
}

func (o *IpamVlanGroupsCreateCreated) String() string {
	return fmt.Sprintf("[POST /ipam/vlan-groups/][%d] ipamVlanGroupsCreateCreated  %+v", 201, o.Payload)
}

func (o *IpamVlanGroupsCreateCreated) GetPayload() *models.VLANGroup {
	return o.Payload
}

func (o *IpamVlanGroupsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VLANGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamVlanGroupsCreateBadRequest creates a IpamVlanGroupsCreateBadRequest with default headers values
func NewIpamVlanGroupsCreateBadRequest() *IpamVlanGroupsCreateBadRequest {
	return &IpamVlanGroupsCreateBadRequest{}
}

/*
IpamVlanGroupsCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamVlanGroupsCreateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam vlan groups create bad request response has a 2xx status code
func (o *IpamVlanGroupsCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam vlan groups create bad request response has a 3xx status code
func (o *IpamVlanGroupsCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vlan groups create bad request response has a 4xx status code
func (o *IpamVlanGroupsCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam vlan groups create bad request response has a 5xx status code
func (o *IpamVlanGroupsCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vlan groups create bad request response a status code equal to that given
func (o *IpamVlanGroupsCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamVlanGroupsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /ipam/vlan-groups/][%d] ipamVlanGroupsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamVlanGroupsCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /ipam/vlan-groups/][%d] ipamVlanGroupsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamVlanGroupsCreateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamVlanGroupsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamVlanGroupsCreateDefault creates a IpamVlanGroupsCreateDefault with default headers values
func NewIpamVlanGroupsCreateDefault(code int) *IpamVlanGroupsCreateDefault {
	return &IpamVlanGroupsCreateDefault{
		_statusCode: code,
	}
}

/*
IpamVlanGroupsCreateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamVlanGroupsCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam vlan groups create default response
func (o *IpamVlanGroupsCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam vlan groups create default response has a 2xx status code
func (o *IpamVlanGroupsCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam vlan groups create default response has a 3xx status code
func (o *IpamVlanGroupsCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam vlan groups create default response has a 4xx status code
func (o *IpamVlanGroupsCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam vlan groups create default response has a 5xx status code
func (o *IpamVlanGroupsCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam vlan groups create default response a status code equal to that given
func (o *IpamVlanGroupsCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamVlanGroupsCreateDefault) Error() string {
	return fmt.Sprintf("[POST /ipam/vlan-groups/][%d] ipam_vlan-groups_create default  %+v", o._statusCode, o.Payload)
}

func (o *IpamVlanGroupsCreateDefault) String() string {
	return fmt.Sprintf("[POST /ipam/vlan-groups/][%d] ipam_vlan-groups_create default  %+v", o._statusCode, o.Payload)
}

func (o *IpamVlanGroupsCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamVlanGroupsCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
