// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamVrfsUpdateReader is a Reader for the IpamVrfsUpdate structure.
type IpamVrfsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamVrfsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamVrfsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamVrfsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamVrfsUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamVrfsUpdateOK creates a IpamVrfsUpdateOK with default headers values
func NewIpamVrfsUpdateOK() *IpamVrfsUpdateOK {
	return &IpamVrfsUpdateOK{}
}

/*
IpamVrfsUpdateOK describes a response with status code 200, with default header values.

IpamVrfsUpdateOK ipam vrfs update o k
*/
type IpamVrfsUpdateOK struct {
	Payload *models.VRF
}

// IsSuccess returns true when this ipam vrfs update o k response has a 2xx status code
func (o *IpamVrfsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam vrfs update o k response has a 3xx status code
func (o *IpamVrfsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vrfs update o k response has a 4xx status code
func (o *IpamVrfsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam vrfs update o k response has a 5xx status code
func (o *IpamVrfsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vrfs update o k response a status code equal to that given
func (o *IpamVrfsUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *IpamVrfsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /ipam/vrfs/{id}/][%d] ipamVrfsUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamVrfsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /ipam/vrfs/{id}/][%d] ipamVrfsUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamVrfsUpdateOK) GetPayload() *models.VRF {
	return o.Payload
}

func (o *IpamVrfsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VRF)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamVrfsUpdateBadRequest creates a IpamVrfsUpdateBadRequest with default headers values
func NewIpamVrfsUpdateBadRequest() *IpamVrfsUpdateBadRequest {
	return &IpamVrfsUpdateBadRequest{}
}

/*
IpamVrfsUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamVrfsUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam vrfs update bad request response has a 2xx status code
func (o *IpamVrfsUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam vrfs update bad request response has a 3xx status code
func (o *IpamVrfsUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vrfs update bad request response has a 4xx status code
func (o *IpamVrfsUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam vrfs update bad request response has a 5xx status code
func (o *IpamVrfsUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vrfs update bad request response a status code equal to that given
func (o *IpamVrfsUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamVrfsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /ipam/vrfs/{id}/][%d] ipamVrfsUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamVrfsUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /ipam/vrfs/{id}/][%d] ipamVrfsUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamVrfsUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamVrfsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamVrfsUpdateDefault creates a IpamVrfsUpdateDefault with default headers values
func NewIpamVrfsUpdateDefault(code int) *IpamVrfsUpdateDefault {
	return &IpamVrfsUpdateDefault{
		_statusCode: code,
	}
}

/*
IpamVrfsUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamVrfsUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam vrfs update default response
func (o *IpamVrfsUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam vrfs update default response has a 2xx status code
func (o *IpamVrfsUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam vrfs update default response has a 3xx status code
func (o *IpamVrfsUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam vrfs update default response has a 4xx status code
func (o *IpamVrfsUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam vrfs update default response has a 5xx status code
func (o *IpamVrfsUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam vrfs update default response a status code equal to that given
func (o *IpamVrfsUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamVrfsUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /ipam/vrfs/{id}/][%d] ipam_vrfs_update default  %+v", o._statusCode, o.Payload)
}

func (o *IpamVrfsUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /ipam/vrfs/{id}/][%d] ipam_vrfs_update default  %+v", o._statusCode, o.Payload)
}

func (o *IpamVrfsUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamVrfsUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
