// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamVrfsReadReader is a Reader for the IpamVrfsRead structure.
type IpamVrfsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamVrfsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamVrfsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamVrfsReadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamVrfsReadDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamVrfsReadOK creates a IpamVrfsReadOK with default headers values
func NewIpamVrfsReadOK() *IpamVrfsReadOK {
	return &IpamVrfsReadOK{}
}

/*
IpamVrfsReadOK describes a response with status code 200, with default header values.

IpamVrfsReadOK ipam vrfs read o k
*/
type IpamVrfsReadOK struct {
	Payload *models.VRF
}

// IsSuccess returns true when this ipam vrfs read o k response has a 2xx status code
func (o *IpamVrfsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam vrfs read o k response has a 3xx status code
func (o *IpamVrfsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vrfs read o k response has a 4xx status code
func (o *IpamVrfsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam vrfs read o k response has a 5xx status code
func (o *IpamVrfsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vrfs read o k response a status code equal to that given
func (o *IpamVrfsReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *IpamVrfsReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/vrfs/{id}/][%d] ipamVrfsReadOK  %+v", 200, o.Payload)
}

func (o *IpamVrfsReadOK) String() string {
	return fmt.Sprintf("[GET /ipam/vrfs/{id}/][%d] ipamVrfsReadOK  %+v", 200, o.Payload)
}

func (o *IpamVrfsReadOK) GetPayload() *models.VRF {
	return o.Payload
}

func (o *IpamVrfsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VRF)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamVrfsReadBadRequest creates a IpamVrfsReadBadRequest with default headers values
func NewIpamVrfsReadBadRequest() *IpamVrfsReadBadRequest {
	return &IpamVrfsReadBadRequest{}
}

/*
IpamVrfsReadBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamVrfsReadBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam vrfs read bad request response has a 2xx status code
func (o *IpamVrfsReadBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam vrfs read bad request response has a 3xx status code
func (o *IpamVrfsReadBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vrfs read bad request response has a 4xx status code
func (o *IpamVrfsReadBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam vrfs read bad request response has a 5xx status code
func (o *IpamVrfsReadBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vrfs read bad request response a status code equal to that given
func (o *IpamVrfsReadBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamVrfsReadBadRequest) Error() string {
	return fmt.Sprintf("[GET /ipam/vrfs/{id}/][%d] ipamVrfsReadBadRequest  %+v", 400, o.Payload)
}

func (o *IpamVrfsReadBadRequest) String() string {
	return fmt.Sprintf("[GET /ipam/vrfs/{id}/][%d] ipamVrfsReadBadRequest  %+v", 400, o.Payload)
}

func (o *IpamVrfsReadBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamVrfsReadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamVrfsReadDefault creates a IpamVrfsReadDefault with default headers values
func NewIpamVrfsReadDefault(code int) *IpamVrfsReadDefault {
	return &IpamVrfsReadDefault{
		_statusCode: code,
	}
}

/*
IpamVrfsReadDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamVrfsReadDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam vrfs read default response
func (o *IpamVrfsReadDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam vrfs read default response has a 2xx status code
func (o *IpamVrfsReadDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam vrfs read default response has a 3xx status code
func (o *IpamVrfsReadDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam vrfs read default response has a 4xx status code
func (o *IpamVrfsReadDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam vrfs read default response has a 5xx status code
func (o *IpamVrfsReadDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam vrfs read default response a status code equal to that given
func (o *IpamVrfsReadDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamVrfsReadDefault) Error() string {
	return fmt.Sprintf("[GET /ipam/vrfs/{id}/][%d] ipam_vrfs_read default  %+v", o._statusCode, o.Payload)
}

func (o *IpamVrfsReadDefault) String() string {
	return fmt.Sprintf("[GET /ipam/vrfs/{id}/][%d] ipam_vrfs_read default  %+v", o._statusCode, o.Payload)
}

func (o *IpamVrfsReadDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamVrfsReadDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
