// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IpamIPAddressesBulkDeleteReader is a Reader for the IpamIPAddressesBulkDelete structure.
type IpamIPAddressesBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamIPAddressesBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewIpamIPAddressesBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamIPAddressesBulkDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamIPAddressesBulkDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamIPAddressesBulkDeleteNoContent creates a IpamIPAddressesBulkDeleteNoContent with default headers values
func NewIpamIPAddressesBulkDeleteNoContent() *IpamIPAddressesBulkDeleteNoContent {
	return &IpamIPAddressesBulkDeleteNoContent{}
}

/*
IpamIPAddressesBulkDeleteNoContent describes a response with status code 204, with default header values.

IpamIPAddressesBulkDeleteNoContent ipam Ip addresses bulk delete no content
*/
type IpamIPAddressesBulkDeleteNoContent struct {
}

// IsSuccess returns true when this ipam Ip addresses bulk delete no content response has a 2xx status code
func (o *IpamIPAddressesBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam Ip addresses bulk delete no content response has a 3xx status code
func (o *IpamIPAddressesBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam Ip addresses bulk delete no content response has a 4xx status code
func (o *IpamIPAddressesBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam Ip addresses bulk delete no content response has a 5xx status code
func (o *IpamIPAddressesBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam Ip addresses bulk delete no content response a status code equal to that given
func (o *IpamIPAddressesBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *IpamIPAddressesBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/ip-addresses/][%d] ipamIpAddressesBulkDeleteNoContent ", 204)
}

func (o *IpamIPAddressesBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /ipam/ip-addresses/][%d] ipamIpAddressesBulkDeleteNoContent ", 204)
}

func (o *IpamIPAddressesBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIpamIPAddressesBulkDeleteBadRequest creates a IpamIPAddressesBulkDeleteBadRequest with default headers values
func NewIpamIPAddressesBulkDeleteBadRequest() *IpamIPAddressesBulkDeleteBadRequest {
	return &IpamIPAddressesBulkDeleteBadRequest{}
}

/*
IpamIPAddressesBulkDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamIPAddressesBulkDeleteBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam Ip addresses bulk delete bad request response has a 2xx status code
func (o *IpamIPAddressesBulkDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam Ip addresses bulk delete bad request response has a 3xx status code
func (o *IpamIPAddressesBulkDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam Ip addresses bulk delete bad request response has a 4xx status code
func (o *IpamIPAddressesBulkDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam Ip addresses bulk delete bad request response has a 5xx status code
func (o *IpamIPAddressesBulkDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam Ip addresses bulk delete bad request response a status code equal to that given
func (o *IpamIPAddressesBulkDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamIPAddressesBulkDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /ipam/ip-addresses/][%d] ipamIpAddressesBulkDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *IpamIPAddressesBulkDeleteBadRequest) String() string {
	return fmt.Sprintf("[DELETE /ipam/ip-addresses/][%d] ipamIpAddressesBulkDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *IpamIPAddressesBulkDeleteBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamIPAddressesBulkDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamIPAddressesBulkDeleteDefault creates a IpamIPAddressesBulkDeleteDefault with default headers values
func NewIpamIPAddressesBulkDeleteDefault(code int) *IpamIPAddressesBulkDeleteDefault {
	return &IpamIPAddressesBulkDeleteDefault{
		_statusCode: code,
	}
}

/*
IpamIPAddressesBulkDeleteDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamIPAddressesBulkDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam ip addresses bulk delete default response
func (o *IpamIPAddressesBulkDeleteDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam ip addresses bulk delete default response has a 2xx status code
func (o *IpamIPAddressesBulkDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam ip addresses bulk delete default response has a 3xx status code
func (o *IpamIPAddressesBulkDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam ip addresses bulk delete default response has a 4xx status code
func (o *IpamIPAddressesBulkDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam ip addresses bulk delete default response has a 5xx status code
func (o *IpamIPAddressesBulkDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam ip addresses bulk delete default response a status code equal to that given
func (o *IpamIPAddressesBulkDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamIPAddressesBulkDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /ipam/ip-addresses/][%d] ipam_ip-addresses_bulk_delete default  %+v", o._statusCode, o.Payload)
}

func (o *IpamIPAddressesBulkDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /ipam/ip-addresses/][%d] ipam_ip-addresses_bulk_delete default  %+v", o._statusCode, o.Payload)
}

func (o *IpamIPAddressesBulkDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamIPAddressesBulkDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
