// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamRouteTargetsReadReader is a Reader for the IpamRouteTargetsRead structure.
type IpamRouteTargetsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamRouteTargetsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamRouteTargetsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamRouteTargetsReadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamRouteTargetsReadDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamRouteTargetsReadOK creates a IpamRouteTargetsReadOK with default headers values
func NewIpamRouteTargetsReadOK() *IpamRouteTargetsReadOK {
	return &IpamRouteTargetsReadOK{}
}

/*
IpamRouteTargetsReadOK describes a response with status code 200, with default header values.

IpamRouteTargetsReadOK ipam route targets read o k
*/
type IpamRouteTargetsReadOK struct {
	Payload *models.RouteTarget
}

// IsSuccess returns true when this ipam route targets read o k response has a 2xx status code
func (o *IpamRouteTargetsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam route targets read o k response has a 3xx status code
func (o *IpamRouteTargetsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam route targets read o k response has a 4xx status code
func (o *IpamRouteTargetsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam route targets read o k response has a 5xx status code
func (o *IpamRouteTargetsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam route targets read o k response a status code equal to that given
func (o *IpamRouteTargetsReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *IpamRouteTargetsReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/route-targets/{id}/][%d] ipamRouteTargetsReadOK  %+v", 200, o.Payload)
}

func (o *IpamRouteTargetsReadOK) String() string {
	return fmt.Sprintf("[GET /ipam/route-targets/{id}/][%d] ipamRouteTargetsReadOK  %+v", 200, o.Payload)
}

func (o *IpamRouteTargetsReadOK) GetPayload() *models.RouteTarget {
	return o.Payload
}

func (o *IpamRouteTargetsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RouteTarget)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamRouteTargetsReadBadRequest creates a IpamRouteTargetsReadBadRequest with default headers values
func NewIpamRouteTargetsReadBadRequest() *IpamRouteTargetsReadBadRequest {
	return &IpamRouteTargetsReadBadRequest{}
}

/*
IpamRouteTargetsReadBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamRouteTargetsReadBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam route targets read bad request response has a 2xx status code
func (o *IpamRouteTargetsReadBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam route targets read bad request response has a 3xx status code
func (o *IpamRouteTargetsReadBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam route targets read bad request response has a 4xx status code
func (o *IpamRouteTargetsReadBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam route targets read bad request response has a 5xx status code
func (o *IpamRouteTargetsReadBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam route targets read bad request response a status code equal to that given
func (o *IpamRouteTargetsReadBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamRouteTargetsReadBadRequest) Error() string {
	return fmt.Sprintf("[GET /ipam/route-targets/{id}/][%d] ipamRouteTargetsReadBadRequest  %+v", 400, o.Payload)
}

func (o *IpamRouteTargetsReadBadRequest) String() string {
	return fmt.Sprintf("[GET /ipam/route-targets/{id}/][%d] ipamRouteTargetsReadBadRequest  %+v", 400, o.Payload)
}

func (o *IpamRouteTargetsReadBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamRouteTargetsReadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamRouteTargetsReadDefault creates a IpamRouteTargetsReadDefault with default headers values
func NewIpamRouteTargetsReadDefault(code int) *IpamRouteTargetsReadDefault {
	return &IpamRouteTargetsReadDefault{
		_statusCode: code,
	}
}

/*
IpamRouteTargetsReadDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamRouteTargetsReadDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam route targets read default response
func (o *IpamRouteTargetsReadDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam route targets read default response has a 2xx status code
func (o *IpamRouteTargetsReadDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam route targets read default response has a 3xx status code
func (o *IpamRouteTargetsReadDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam route targets read default response has a 4xx status code
func (o *IpamRouteTargetsReadDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam route targets read default response has a 5xx status code
func (o *IpamRouteTargetsReadDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam route targets read default response a status code equal to that given
func (o *IpamRouteTargetsReadDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamRouteTargetsReadDefault) Error() string {
	return fmt.Sprintf("[GET /ipam/route-targets/{id}/][%d] ipam_route-targets_read default  %+v", o._statusCode, o.Payload)
}

func (o *IpamRouteTargetsReadDefault) String() string {
	return fmt.Sprintf("[GET /ipam/route-targets/{id}/][%d] ipam_route-targets_read default  %+v", o._statusCode, o.Payload)
}

func (o *IpamRouteTargetsReadDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamRouteTargetsReadDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
