// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IpamAsnsBulkDeleteReader is a Reader for the IpamAsnsBulkDelete structure.
type IpamAsnsBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamAsnsBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewIpamAsnsBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamAsnsBulkDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamAsnsBulkDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamAsnsBulkDeleteNoContent creates a IpamAsnsBulkDeleteNoContent with default headers values
func NewIpamAsnsBulkDeleteNoContent() *IpamAsnsBulkDeleteNoContent {
	return &IpamAsnsBulkDeleteNoContent{}
}

/*
IpamAsnsBulkDeleteNoContent describes a response with status code 204, with default header values.

IpamAsnsBulkDeleteNoContent ipam asns bulk delete no content
*/
type IpamAsnsBulkDeleteNoContent struct {
}

// IsSuccess returns true when this ipam asns bulk delete no content response has a 2xx status code
func (o *IpamAsnsBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam asns bulk delete no content response has a 3xx status code
func (o *IpamAsnsBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam asns bulk delete no content response has a 4xx status code
func (o *IpamAsnsBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam asns bulk delete no content response has a 5xx status code
func (o *IpamAsnsBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam asns bulk delete no content response a status code equal to that given
func (o *IpamAsnsBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *IpamAsnsBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/asns/][%d] ipamAsnsBulkDeleteNoContent ", 204)
}

func (o *IpamAsnsBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /ipam/asns/][%d] ipamAsnsBulkDeleteNoContent ", 204)
}

func (o *IpamAsnsBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIpamAsnsBulkDeleteBadRequest creates a IpamAsnsBulkDeleteBadRequest with default headers values
func NewIpamAsnsBulkDeleteBadRequest() *IpamAsnsBulkDeleteBadRequest {
	return &IpamAsnsBulkDeleteBadRequest{}
}

/*
IpamAsnsBulkDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamAsnsBulkDeleteBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam asns bulk delete bad request response has a 2xx status code
func (o *IpamAsnsBulkDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam asns bulk delete bad request response has a 3xx status code
func (o *IpamAsnsBulkDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam asns bulk delete bad request response has a 4xx status code
func (o *IpamAsnsBulkDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam asns bulk delete bad request response has a 5xx status code
func (o *IpamAsnsBulkDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam asns bulk delete bad request response a status code equal to that given
func (o *IpamAsnsBulkDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamAsnsBulkDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /ipam/asns/][%d] ipamAsnsBulkDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *IpamAsnsBulkDeleteBadRequest) String() string {
	return fmt.Sprintf("[DELETE /ipam/asns/][%d] ipamAsnsBulkDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *IpamAsnsBulkDeleteBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamAsnsBulkDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamAsnsBulkDeleteDefault creates a IpamAsnsBulkDeleteDefault with default headers values
func NewIpamAsnsBulkDeleteDefault(code int) *IpamAsnsBulkDeleteDefault {
	return &IpamAsnsBulkDeleteDefault{
		_statusCode: code,
	}
}

/*
IpamAsnsBulkDeleteDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamAsnsBulkDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam asns bulk delete default response
func (o *IpamAsnsBulkDeleteDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam asns bulk delete default response has a 2xx status code
func (o *IpamAsnsBulkDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam asns bulk delete default response has a 3xx status code
func (o *IpamAsnsBulkDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam asns bulk delete default response has a 4xx status code
func (o *IpamAsnsBulkDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam asns bulk delete default response has a 5xx status code
func (o *IpamAsnsBulkDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam asns bulk delete default response a status code equal to that given
func (o *IpamAsnsBulkDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamAsnsBulkDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /ipam/asns/][%d] ipam_asns_bulk_delete default  %+v", o._statusCode, o.Payload)
}

func (o *IpamAsnsBulkDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /ipam/asns/][%d] ipam_asns_bulk_delete default  %+v", o._statusCode, o.Payload)
}

func (o *IpamAsnsBulkDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamAsnsBulkDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
