// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamL2vpnsCreateReader is a Reader for the IpamL2vpnsCreate structure.
type IpamL2vpnsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamL2vpnsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIpamL2vpnsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamL2vpnsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamL2vpnsCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamL2vpnsCreateCreated creates a IpamL2vpnsCreateCreated with default headers values
func NewIpamL2vpnsCreateCreated() *IpamL2vpnsCreateCreated {
	return &IpamL2vpnsCreateCreated{}
}

/*
IpamL2vpnsCreateCreated describes a response with status code 201, with default header values.

IpamL2vpnsCreateCreated ipam l2vpns create created
*/
type IpamL2vpnsCreateCreated struct {
	Payload *models.L2VPN
}

// IsSuccess returns true when this ipam l2vpns create created response has a 2xx status code
func (o *IpamL2vpnsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam l2vpns create created response has a 3xx status code
func (o *IpamL2vpnsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam l2vpns create created response has a 4xx status code
func (o *IpamL2vpnsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam l2vpns create created response has a 5xx status code
func (o *IpamL2vpnsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam l2vpns create created response a status code equal to that given
func (o *IpamL2vpnsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *IpamL2vpnsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/l2vpns/][%d] ipamL2vpnsCreateCreated  %+v", 201, o.Payload)
}

func (o *IpamL2vpnsCreateCreated) String() string {
	return fmt.Sprintf("[POST /ipam/l2vpns/][%d] ipamL2vpnsCreateCreated  %+v", 201, o.Payload)
}

func (o *IpamL2vpnsCreateCreated) GetPayload() *models.L2VPN {
	return o.Payload
}

func (o *IpamL2vpnsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.L2VPN)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamL2vpnsCreateBadRequest creates a IpamL2vpnsCreateBadRequest with default headers values
func NewIpamL2vpnsCreateBadRequest() *IpamL2vpnsCreateBadRequest {
	return &IpamL2vpnsCreateBadRequest{}
}

/*
IpamL2vpnsCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamL2vpnsCreateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam l2vpns create bad request response has a 2xx status code
func (o *IpamL2vpnsCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam l2vpns create bad request response has a 3xx status code
func (o *IpamL2vpnsCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam l2vpns create bad request response has a 4xx status code
func (o *IpamL2vpnsCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam l2vpns create bad request response has a 5xx status code
func (o *IpamL2vpnsCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam l2vpns create bad request response a status code equal to that given
func (o *IpamL2vpnsCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamL2vpnsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /ipam/l2vpns/][%d] ipamL2vpnsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamL2vpnsCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /ipam/l2vpns/][%d] ipamL2vpnsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamL2vpnsCreateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamL2vpnsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamL2vpnsCreateDefault creates a IpamL2vpnsCreateDefault with default headers values
func NewIpamL2vpnsCreateDefault(code int) *IpamL2vpnsCreateDefault {
	return &IpamL2vpnsCreateDefault{
		_statusCode: code,
	}
}

/*
IpamL2vpnsCreateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamL2vpnsCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam l2vpns create default response
func (o *IpamL2vpnsCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam l2vpns create default response has a 2xx status code
func (o *IpamL2vpnsCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam l2vpns create default response has a 3xx status code
func (o *IpamL2vpnsCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam l2vpns create default response has a 4xx status code
func (o *IpamL2vpnsCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam l2vpns create default response has a 5xx status code
func (o *IpamL2vpnsCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam l2vpns create default response a status code equal to that given
func (o *IpamL2vpnsCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamL2vpnsCreateDefault) Error() string {
	return fmt.Sprintf("[POST /ipam/l2vpns/][%d] ipam_l2vpns_create default  %+v", o._statusCode, o.Payload)
}

func (o *IpamL2vpnsCreateDefault) String() string {
	return fmt.Sprintf("[POST /ipam/l2vpns/][%d] ipam_l2vpns_create default  %+v", o._statusCode, o.Payload)
}

func (o *IpamL2vpnsCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamL2vpnsCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
