// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// IpamAsnsUpdateReader is a Reader for the IpamAsnsUpdate structure.
type IpamAsnsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamAsnsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamAsnsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIpamAsnsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIpamAsnsUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamAsnsUpdateOK creates a IpamAsnsUpdateOK with default headers values
func NewIpamAsnsUpdateOK() *IpamAsnsUpdateOK {
	return &IpamAsnsUpdateOK{}
}

/*
IpamAsnsUpdateOK describes a response with status code 200, with default header values.

IpamAsnsUpdateOK ipam asns update o k
*/
type IpamAsnsUpdateOK struct {
	Payload *models.ASN
}

// IsSuccess returns true when this ipam asns update o k response has a 2xx status code
func (o *IpamAsnsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam asns update o k response has a 3xx status code
func (o *IpamAsnsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam asns update o k response has a 4xx status code
func (o *IpamAsnsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam asns update o k response has a 5xx status code
func (o *IpamAsnsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam asns update o k response a status code equal to that given
func (o *IpamAsnsUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *IpamAsnsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /ipam/asns/{id}/][%d] ipamAsnsUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamAsnsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /ipam/asns/{id}/][%d] ipamAsnsUpdateOK  %+v", 200, o.Payload)
}

func (o *IpamAsnsUpdateOK) GetPayload() *models.ASN {
	return o.Payload
}

func (o *IpamAsnsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ASN)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamAsnsUpdateBadRequest creates a IpamAsnsUpdateBadRequest with default headers values
func NewIpamAsnsUpdateBadRequest() *IpamAsnsUpdateBadRequest {
	return &IpamAsnsUpdateBadRequest{}
}

/*
IpamAsnsUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type IpamAsnsUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this ipam asns update bad request response has a 2xx status code
func (o *IpamAsnsUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ipam asns update bad request response has a 3xx status code
func (o *IpamAsnsUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam asns update bad request response has a 4xx status code
func (o *IpamAsnsUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ipam asns update bad request response has a 5xx status code
func (o *IpamAsnsUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam asns update bad request response a status code equal to that given
func (o *IpamAsnsUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *IpamAsnsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /ipam/asns/{id}/][%d] ipamAsnsUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamAsnsUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /ipam/asns/{id}/][%d] ipamAsnsUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *IpamAsnsUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamAsnsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamAsnsUpdateDefault creates a IpamAsnsUpdateDefault with default headers values
func NewIpamAsnsUpdateDefault(code int) *IpamAsnsUpdateDefault {
	return &IpamAsnsUpdateDefault{
		_statusCode: code,
	}
}

/*
IpamAsnsUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type IpamAsnsUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam asns update default response
func (o *IpamAsnsUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this ipam asns update default response has a 2xx status code
func (o *IpamAsnsUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ipam asns update default response has a 3xx status code
func (o *IpamAsnsUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ipam asns update default response has a 4xx status code
func (o *IpamAsnsUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ipam asns update default response has a 5xx status code
func (o *IpamAsnsUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ipam asns update default response a status code equal to that given
func (o *IpamAsnsUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IpamAsnsUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /ipam/asns/{id}/][%d] ipam_asns_update default  %+v", o._statusCode, o.Payload)
}

func (o *IpamAsnsUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /ipam/asns/{id}/][%d] ipam_asns_update default  %+v", o._statusCode, o.Payload)
}

func (o *IpamAsnsUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamAsnsUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
