// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// DcimInventoryItemsReadReader is a Reader for the DcimInventoryItemsRead structure.
type DcimInventoryItemsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimInventoryItemsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimInventoryItemsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDcimInventoryItemsReadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDcimInventoryItemsReadDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimInventoryItemsReadOK creates a DcimInventoryItemsReadOK with default headers values
func NewDcimInventoryItemsReadOK() *DcimInventoryItemsReadOK {
	return &DcimInventoryItemsReadOK{}
}

/*
DcimInventoryItemsReadOK describes a response with status code 200, with default header values.

DcimInventoryItemsReadOK dcim inventory items read o k
*/
type DcimInventoryItemsReadOK struct {
	Payload *models.InventoryItem
}

// IsSuccess returns true when this dcim inventory items read o k response has a 2xx status code
func (o *DcimInventoryItemsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim inventory items read o k response has a 3xx status code
func (o *DcimInventoryItemsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim inventory items read o k response has a 4xx status code
func (o *DcimInventoryItemsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim inventory items read o k response has a 5xx status code
func (o *DcimInventoryItemsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim inventory items read o k response a status code equal to that given
func (o *DcimInventoryItemsReadOK) IsCode(code int) bool {
	return code == 200
}

func (o *DcimInventoryItemsReadOK) Error() string {
	return fmt.Sprintf("[GET /dcim/inventory-items/{id}/][%d] dcimInventoryItemsReadOK  %+v", 200, o.Payload)
}

func (o *DcimInventoryItemsReadOK) String() string {
	return fmt.Sprintf("[GET /dcim/inventory-items/{id}/][%d] dcimInventoryItemsReadOK  %+v", 200, o.Payload)
}

func (o *DcimInventoryItemsReadOK) GetPayload() *models.InventoryItem {
	return o.Payload
}

func (o *DcimInventoryItemsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InventoryItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimInventoryItemsReadBadRequest creates a DcimInventoryItemsReadBadRequest with default headers values
func NewDcimInventoryItemsReadBadRequest() *DcimInventoryItemsReadBadRequest {
	return &DcimInventoryItemsReadBadRequest{}
}

/*
DcimInventoryItemsReadBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DcimInventoryItemsReadBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this dcim inventory items read bad request response has a 2xx status code
func (o *DcimInventoryItemsReadBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this dcim inventory items read bad request response has a 3xx status code
func (o *DcimInventoryItemsReadBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim inventory items read bad request response has a 4xx status code
func (o *DcimInventoryItemsReadBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this dcim inventory items read bad request response has a 5xx status code
func (o *DcimInventoryItemsReadBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim inventory items read bad request response a status code equal to that given
func (o *DcimInventoryItemsReadBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DcimInventoryItemsReadBadRequest) Error() string {
	return fmt.Sprintf("[GET /dcim/inventory-items/{id}/][%d] dcimInventoryItemsReadBadRequest  %+v", 400, o.Payload)
}

func (o *DcimInventoryItemsReadBadRequest) String() string {
	return fmt.Sprintf("[GET /dcim/inventory-items/{id}/][%d] dcimInventoryItemsReadBadRequest  %+v", 400, o.Payload)
}

func (o *DcimInventoryItemsReadBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimInventoryItemsReadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimInventoryItemsReadDefault creates a DcimInventoryItemsReadDefault with default headers values
func NewDcimInventoryItemsReadDefault(code int) *DcimInventoryItemsReadDefault {
	return &DcimInventoryItemsReadDefault{
		_statusCode: code,
	}
}

/*
DcimInventoryItemsReadDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type DcimInventoryItemsReadDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the dcim inventory items read default response
func (o *DcimInventoryItemsReadDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this dcim inventory items read default response has a 2xx status code
func (o *DcimInventoryItemsReadDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim inventory items read default response has a 3xx status code
func (o *DcimInventoryItemsReadDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim inventory items read default response has a 4xx status code
func (o *DcimInventoryItemsReadDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim inventory items read default response has a 5xx status code
func (o *DcimInventoryItemsReadDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim inventory items read default response a status code equal to that given
func (o *DcimInventoryItemsReadDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DcimInventoryItemsReadDefault) Error() string {
	return fmt.Sprintf("[GET /dcim/inventory-items/{id}/][%d] dcim_inventory-items_read default  %+v", o._statusCode, o.Payload)
}

func (o *DcimInventoryItemsReadDefault) String() string {
	return fmt.Sprintf("[GET /dcim/inventory-items/{id}/][%d] dcim_inventory-items_read default  %+v", o._statusCode, o.Payload)
}

func (o *DcimInventoryItemsReadDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimInventoryItemsReadDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
