// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// DcimCablesBulkUpdateReader is a Reader for the DcimCablesBulkUpdate structure.
type DcimCablesBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimCablesBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimCablesBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDcimCablesBulkUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDcimCablesBulkUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimCablesBulkUpdateOK creates a DcimCablesBulkUpdateOK with default headers values
func NewDcimCablesBulkUpdateOK() *DcimCablesBulkUpdateOK {
	return &DcimCablesBulkUpdateOK{}
}

/*
DcimCablesBulkUpdateOK describes a response with status code 200, with default header values.

DcimCablesBulkUpdateOK dcim cables bulk update o k
*/
type DcimCablesBulkUpdateOK struct {
	Payload *models.Cable
}

// IsSuccess returns true when this dcim cables bulk update o k response has a 2xx status code
func (o *DcimCablesBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim cables bulk update o k response has a 3xx status code
func (o *DcimCablesBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim cables bulk update o k response has a 4xx status code
func (o *DcimCablesBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim cables bulk update o k response has a 5xx status code
func (o *DcimCablesBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim cables bulk update o k response a status code equal to that given
func (o *DcimCablesBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *DcimCablesBulkUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /dcim/cables/][%d] dcimCablesBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *DcimCablesBulkUpdateOK) String() string {
	return fmt.Sprintf("[PUT /dcim/cables/][%d] dcimCablesBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *DcimCablesBulkUpdateOK) GetPayload() *models.Cable {
	return o.Payload
}

func (o *DcimCablesBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimCablesBulkUpdateBadRequest creates a DcimCablesBulkUpdateBadRequest with default headers values
func NewDcimCablesBulkUpdateBadRequest() *DcimCablesBulkUpdateBadRequest {
	return &DcimCablesBulkUpdateBadRequest{}
}

/*
DcimCablesBulkUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DcimCablesBulkUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this dcim cables bulk update bad request response has a 2xx status code
func (o *DcimCablesBulkUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this dcim cables bulk update bad request response has a 3xx status code
func (o *DcimCablesBulkUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim cables bulk update bad request response has a 4xx status code
func (o *DcimCablesBulkUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this dcim cables bulk update bad request response has a 5xx status code
func (o *DcimCablesBulkUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim cables bulk update bad request response a status code equal to that given
func (o *DcimCablesBulkUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DcimCablesBulkUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /dcim/cables/][%d] dcimCablesBulkUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *DcimCablesBulkUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /dcim/cables/][%d] dcimCablesBulkUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *DcimCablesBulkUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimCablesBulkUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimCablesBulkUpdateDefault creates a DcimCablesBulkUpdateDefault with default headers values
func NewDcimCablesBulkUpdateDefault(code int) *DcimCablesBulkUpdateDefault {
	return &DcimCablesBulkUpdateDefault{
		_statusCode: code,
	}
}

/*
DcimCablesBulkUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type DcimCablesBulkUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the dcim cables bulk update default response
func (o *DcimCablesBulkUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this dcim cables bulk update default response has a 2xx status code
func (o *DcimCablesBulkUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim cables bulk update default response has a 3xx status code
func (o *DcimCablesBulkUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim cables bulk update default response has a 4xx status code
func (o *DcimCablesBulkUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim cables bulk update default response has a 5xx status code
func (o *DcimCablesBulkUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim cables bulk update default response a status code equal to that given
func (o *DcimCablesBulkUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DcimCablesBulkUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /dcim/cables/][%d] dcim_cables_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *DcimCablesBulkUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /dcim/cables/][%d] dcim_cables_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *DcimCablesBulkUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimCablesBulkUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
