// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// DcimPlatformsBulkPartialUpdateReader is a Reader for the DcimPlatformsBulkPartialUpdate structure.
type DcimPlatformsBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPlatformsBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimPlatformsBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDcimPlatformsBulkPartialUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDcimPlatformsBulkPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimPlatformsBulkPartialUpdateOK creates a DcimPlatformsBulkPartialUpdateOK with default headers values
func NewDcimPlatformsBulkPartialUpdateOK() *DcimPlatformsBulkPartialUpdateOK {
	return &DcimPlatformsBulkPartialUpdateOK{}
}

/*
DcimPlatformsBulkPartialUpdateOK describes a response with status code 200, with default header values.

DcimPlatformsBulkPartialUpdateOK dcim platforms bulk partial update o k
*/
type DcimPlatformsBulkPartialUpdateOK struct {
	Payload *models.Platform
}

// IsSuccess returns true when this dcim platforms bulk partial update o k response has a 2xx status code
func (o *DcimPlatformsBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim platforms bulk partial update o k response has a 3xx status code
func (o *DcimPlatformsBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim platforms bulk partial update o k response has a 4xx status code
func (o *DcimPlatformsBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim platforms bulk partial update o k response has a 5xx status code
func (o *DcimPlatformsBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim platforms bulk partial update o k response a status code equal to that given
func (o *DcimPlatformsBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *DcimPlatformsBulkPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /dcim/platforms/][%d] dcimPlatformsBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *DcimPlatformsBulkPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /dcim/platforms/][%d] dcimPlatformsBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *DcimPlatformsBulkPartialUpdateOK) GetPayload() *models.Platform {
	return o.Payload
}

func (o *DcimPlatformsBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Platform)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimPlatformsBulkPartialUpdateBadRequest creates a DcimPlatformsBulkPartialUpdateBadRequest with default headers values
func NewDcimPlatformsBulkPartialUpdateBadRequest() *DcimPlatformsBulkPartialUpdateBadRequest {
	return &DcimPlatformsBulkPartialUpdateBadRequest{}
}

/*
DcimPlatformsBulkPartialUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DcimPlatformsBulkPartialUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this dcim platforms bulk partial update bad request response has a 2xx status code
func (o *DcimPlatformsBulkPartialUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this dcim platforms bulk partial update bad request response has a 3xx status code
func (o *DcimPlatformsBulkPartialUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim platforms bulk partial update bad request response has a 4xx status code
func (o *DcimPlatformsBulkPartialUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this dcim platforms bulk partial update bad request response has a 5xx status code
func (o *DcimPlatformsBulkPartialUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim platforms bulk partial update bad request response a status code equal to that given
func (o *DcimPlatformsBulkPartialUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DcimPlatformsBulkPartialUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /dcim/platforms/][%d] dcimPlatformsBulkPartialUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *DcimPlatformsBulkPartialUpdateBadRequest) String() string {
	return fmt.Sprintf("[PATCH /dcim/platforms/][%d] dcimPlatformsBulkPartialUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *DcimPlatformsBulkPartialUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimPlatformsBulkPartialUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimPlatformsBulkPartialUpdateDefault creates a DcimPlatformsBulkPartialUpdateDefault with default headers values
func NewDcimPlatformsBulkPartialUpdateDefault(code int) *DcimPlatformsBulkPartialUpdateDefault {
	return &DcimPlatformsBulkPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
DcimPlatformsBulkPartialUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type DcimPlatformsBulkPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the dcim platforms bulk partial update default response
func (o *DcimPlatformsBulkPartialUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this dcim platforms bulk partial update default response has a 2xx status code
func (o *DcimPlatformsBulkPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim platforms bulk partial update default response has a 3xx status code
func (o *DcimPlatformsBulkPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim platforms bulk partial update default response has a 4xx status code
func (o *DcimPlatformsBulkPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim platforms bulk partial update default response has a 5xx status code
func (o *DcimPlatformsBulkPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim platforms bulk partial update default response a status code equal to that given
func (o *DcimPlatformsBulkPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DcimPlatformsBulkPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /dcim/platforms/][%d] dcim_platforms_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *DcimPlatformsBulkPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /dcim/platforms/][%d] dcim_platforms_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *DcimPlatformsBulkPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimPlatformsBulkPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
