// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// DcimInterfaceTemplatesBulkPartialUpdateReader is a Reader for the DcimInterfaceTemplatesBulkPartialUpdate structure.
type DcimInterfaceTemplatesBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimInterfaceTemplatesBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimInterfaceTemplatesBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDcimInterfaceTemplatesBulkPartialUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDcimInterfaceTemplatesBulkPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimInterfaceTemplatesBulkPartialUpdateOK creates a DcimInterfaceTemplatesBulkPartialUpdateOK with default headers values
func NewDcimInterfaceTemplatesBulkPartialUpdateOK() *DcimInterfaceTemplatesBulkPartialUpdateOK {
	return &DcimInterfaceTemplatesBulkPartialUpdateOK{}
}

/*
DcimInterfaceTemplatesBulkPartialUpdateOK describes a response with status code 200, with default header values.

DcimInterfaceTemplatesBulkPartialUpdateOK dcim interface templates bulk partial update o k
*/
type DcimInterfaceTemplatesBulkPartialUpdateOK struct {
	Payload *models.InterfaceTemplate
}

// IsSuccess returns true when this dcim interface templates bulk partial update o k response has a 2xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim interface templates bulk partial update o k response has a 3xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim interface templates bulk partial update o k response has a 4xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim interface templates bulk partial update o k response has a 5xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim interface templates bulk partial update o k response a status code equal to that given
func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /dcim/interface-templates/][%d] dcimInterfaceTemplatesBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /dcim/interface-templates/][%d] dcimInterfaceTemplatesBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) GetPayload() *models.InterfaceTemplate {
	return o.Payload
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InterfaceTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimInterfaceTemplatesBulkPartialUpdateBadRequest creates a DcimInterfaceTemplatesBulkPartialUpdateBadRequest with default headers values
func NewDcimInterfaceTemplatesBulkPartialUpdateBadRequest() *DcimInterfaceTemplatesBulkPartialUpdateBadRequest {
	return &DcimInterfaceTemplatesBulkPartialUpdateBadRequest{}
}

/*
DcimInterfaceTemplatesBulkPartialUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DcimInterfaceTemplatesBulkPartialUpdateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this dcim interface templates bulk partial update bad request response has a 2xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this dcim interface templates bulk partial update bad request response has a 3xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim interface templates bulk partial update bad request response has a 4xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this dcim interface templates bulk partial update bad request response has a 5xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim interface templates bulk partial update bad request response a status code equal to that given
func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /dcim/interface-templates/][%d] dcimInterfaceTemplatesBulkPartialUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) String() string {
	return fmt.Sprintf("[PATCH /dcim/interface-templates/][%d] dcimInterfaceTemplatesBulkPartialUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimInterfaceTemplatesBulkPartialUpdateDefault creates a DcimInterfaceTemplatesBulkPartialUpdateDefault with default headers values
func NewDcimInterfaceTemplatesBulkPartialUpdateDefault(code int) *DcimInterfaceTemplatesBulkPartialUpdateDefault {
	return &DcimInterfaceTemplatesBulkPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
DcimInterfaceTemplatesBulkPartialUpdateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type DcimInterfaceTemplatesBulkPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the dcim interface templates bulk partial update default response
func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this dcim interface templates bulk partial update default response has a 2xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim interface templates bulk partial update default response has a 3xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim interface templates bulk partial update default response has a 4xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim interface templates bulk partial update default response has a 5xx status code
func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim interface templates bulk partial update default response a status code equal to that given
func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /dcim/interface-templates/][%d] dcim_interface-templates_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /dcim/interface-templates/][%d] dcim_interface-templates_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimInterfaceTemplatesBulkPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
