// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smutel/go-netbox/v3/netbox/models"
)

// DcimCableTerminationsCreateReader is a Reader for the DcimCableTerminationsCreate structure.
type DcimCableTerminationsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimCableTerminationsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDcimCableTerminationsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDcimCableTerminationsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDcimCableTerminationsCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimCableTerminationsCreateCreated creates a DcimCableTerminationsCreateCreated with default headers values
func NewDcimCableTerminationsCreateCreated() *DcimCableTerminationsCreateCreated {
	return &DcimCableTerminationsCreateCreated{}
}

/*
DcimCableTerminationsCreateCreated describes a response with status code 201, with default header values.

DcimCableTerminationsCreateCreated dcim cable terminations create created
*/
type DcimCableTerminationsCreateCreated struct {
	Payload *models.CableTermination
}

// IsSuccess returns true when this dcim cable terminations create created response has a 2xx status code
func (o *DcimCableTerminationsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim cable terminations create created response has a 3xx status code
func (o *DcimCableTerminationsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim cable terminations create created response has a 4xx status code
func (o *DcimCableTerminationsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim cable terminations create created response has a 5xx status code
func (o *DcimCableTerminationsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim cable terminations create created response a status code equal to that given
func (o *DcimCableTerminationsCreateCreated) IsCode(code int) bool {
	return code == 201
}

func (o *DcimCableTerminationsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /dcim/cable-terminations/][%d] dcimCableTerminationsCreateCreated  %+v", 201, o.Payload)
}

func (o *DcimCableTerminationsCreateCreated) String() string {
	return fmt.Sprintf("[POST /dcim/cable-terminations/][%d] dcimCableTerminationsCreateCreated  %+v", 201, o.Payload)
}

func (o *DcimCableTerminationsCreateCreated) GetPayload() *models.CableTermination {
	return o.Payload
}

func (o *DcimCableTerminationsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CableTermination)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimCableTerminationsCreateBadRequest creates a DcimCableTerminationsCreateBadRequest with default headers values
func NewDcimCableTerminationsCreateBadRequest() *DcimCableTerminationsCreateBadRequest {
	return &DcimCableTerminationsCreateBadRequest{}
}

/*
DcimCableTerminationsCreateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DcimCableTerminationsCreateBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this dcim cable terminations create bad request response has a 2xx status code
func (o *DcimCableTerminationsCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this dcim cable terminations create bad request response has a 3xx status code
func (o *DcimCableTerminationsCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim cable terminations create bad request response has a 4xx status code
func (o *DcimCableTerminationsCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this dcim cable terminations create bad request response has a 5xx status code
func (o *DcimCableTerminationsCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim cable terminations create bad request response a status code equal to that given
func (o *DcimCableTerminationsCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DcimCableTerminationsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /dcim/cable-terminations/][%d] dcimCableTerminationsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *DcimCableTerminationsCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /dcim/cable-terminations/][%d] dcimCableTerminationsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *DcimCableTerminationsCreateBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimCableTerminationsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimCableTerminationsCreateDefault creates a DcimCableTerminationsCreateDefault with default headers values
func NewDcimCableTerminationsCreateDefault(code int) *DcimCableTerminationsCreateDefault {
	return &DcimCableTerminationsCreateDefault{
		_statusCode: code,
	}
}

/*
DcimCableTerminationsCreateDefault describes a response with status code -1, with default header values.

Unexpected Response
*/
type DcimCableTerminationsCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the dcim cable terminations create default response
func (o *DcimCableTerminationsCreateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this dcim cable terminations create default response has a 2xx status code
func (o *DcimCableTerminationsCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim cable terminations create default response has a 3xx status code
func (o *DcimCableTerminationsCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim cable terminations create default response has a 4xx status code
func (o *DcimCableTerminationsCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim cable terminations create default response has a 5xx status code
func (o *DcimCableTerminationsCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim cable terminations create default response a status code equal to that given
func (o *DcimCableTerminationsCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DcimCableTerminationsCreateDefault) Error() string {
	return fmt.Sprintf("[POST /dcim/cable-terminations/][%d] dcim_cable-terminations_create default  %+v", o._statusCode, o.Payload)
}

func (o *DcimCableTerminationsCreateDefault) String() string {
	return fmt.Sprintf("[POST /dcim/cable-terminations/][%d] dcim_cable-terminations_create default  %+v", o._statusCode, o.Payload)
}

func (o *DcimCableTerminationsCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimCableTerminationsCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
