// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2020 Samuel Mutel <12967891+smutel@users.noreply.github.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UsersGroupsBulkDeleteReader is a Reader for the UsersGroupsBulkDelete structure.
type UsersGroupsBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersGroupsBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUsersGroupsBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUsersGroupsBulkDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUsersGroupsBulkDeleteNoContent creates a UsersGroupsBulkDeleteNoContent with default headers values
func NewUsersGroupsBulkDeleteNoContent() *UsersGroupsBulkDeleteNoContent {
	return &UsersGroupsBulkDeleteNoContent{}
}

/*
UsersGroupsBulkDeleteNoContent describes a response with status code 204, with default header values.

UsersGroupsBulkDeleteNoContent users groups bulk delete no content
*/
type UsersGroupsBulkDeleteNoContent struct {
}

// IsSuccess returns true when this users groups bulk delete no content response has a 2xx status code
func (o *UsersGroupsBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users groups bulk delete no content response has a 3xx status code
func (o *UsersGroupsBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users groups bulk delete no content response has a 4xx status code
func (o *UsersGroupsBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this users groups bulk delete no content response has a 5xx status code
func (o *UsersGroupsBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this users groups bulk delete no content response a status code equal to that given
func (o *UsersGroupsBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *UsersGroupsBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/groups/][%d] usersGroupsBulkDeleteNoContent ", 204)
}

func (o *UsersGroupsBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /users/groups/][%d] usersGroupsBulkDeleteNoContent ", 204)
}

func (o *UsersGroupsBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUsersGroupsBulkDeleteBadRequest creates a UsersGroupsBulkDeleteBadRequest with default headers values
func NewUsersGroupsBulkDeleteBadRequest() *UsersGroupsBulkDeleteBadRequest {
	return &UsersGroupsBulkDeleteBadRequest{}
}

/*
UsersGroupsBulkDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UsersGroupsBulkDeleteBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this users groups bulk delete bad request response has a 2xx status code
func (o *UsersGroupsBulkDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this users groups bulk delete bad request response has a 3xx status code
func (o *UsersGroupsBulkDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users groups bulk delete bad request response has a 4xx status code
func (o *UsersGroupsBulkDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this users groups bulk delete bad request response has a 5xx status code
func (o *UsersGroupsBulkDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this users groups bulk delete bad request response a status code equal to that given
func (o *UsersGroupsBulkDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *UsersGroupsBulkDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /users/groups/][%d] usersGroupsBulkDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *UsersGroupsBulkDeleteBadRequest) String() string {
	return fmt.Sprintf("[DELETE /users/groups/][%d] usersGroupsBulkDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *UsersGroupsBulkDeleteBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *UsersGroupsBulkDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
